<!-- Megan HTML -->

<div class="one btcf">
    <div id="ti_checkout_BillingInfo" class="btcf">
        <div class="ti_cms_block_headerBar-green"><!-- As user navigates through steps, this class should turn to ti_cms_block_headerBar-orange -->
            <h2 class="white ti_headerH1" id="ti_checkoutStep1"><span class="ti_checkoutStep">1</span> Billing Information</h2>
        </div>
        <!--Billing info shows by default-->
        <div class="one_half ti-required-entry">
            <label class="ti_cms_labelHide">
                <span>First Name</span>
                <input class="required-entry ti_checkout_info" type="text" value="First Name"onfocus="if(this.value=='First Name')this.value='';" onblur="if(this.value=='')this.value='First Name';"/>
            </label>
        </div>
        <div class="one_half ti-required-entry">
            <label class="ti_cms_labelHide">
                <span>Last Name</span>
                <input class="required-entry ti_checkout_info" type="text" value="Last Name"onfocus="if(this.value=='Last Name')this.value='';" onblur="if(this.value=='')this.value='Last Name';">
            </label>
        </div>
        <div class="one_half ti-required-entry">
            <label class="ti_cms_labelHide">
                <span>Email</span>
                <input class="required-entry ti_checkout_info" type="text" value="Email"onfocus="if(this.value=='Email')this.value='';" onblur="if(this.value=='')this.value='Email';">
            </label>
        </div>
        <div class="one_half">
            <label class="ti_cms_labelHide">
                <span>Company</span>
                <input class="ti_checkout_info" type="text" value="Company" onfocus="if(this.value=='Company')this.value='';" onblur="if(this.value=='')this.value='Company';">
            </label>
        </div>
        <div class="one ti-required-entry">
            <label class="ti_cms_labelHide">
                <span>Address line 1</span>
                <input class="required-entry ti_checkout_info" type="text" value="Address" onfocus="if(this.value=='Address')this.value='';" onblur="if(this.value=='')this.value='Address';">
            </label>
        </div>
        <div class="one">
            <label class="ti_cms_labelHide">
                <span>Address line 2</span>
                <input class="ti_checkout_info" type="text">
            </label>
        </div>
        <div class="one_half ti-required-entry">
            <label class="ti_cms_labelHide">
                <span>City</span>
                <input class="required-entry ti_checkout_info" type="text" value="City" onfocus="if(this.value=='City')this.value='';" onblur="if(this.value=='')this.value='City';">
            </label>
        </div>
        <div class="one_half ti-required-entry">
            <label class="ti_cms_labelHide">
                <span>Zip Code</span>
                <input class="required-entry ti_checkout_info" type="text" value="Zip" onfocus="if(this.value=='Zip')this.value='';" onblur="if(this.value=='')this.value='Zip';">
            </label>
        </div>
        <div class="one_half ti-required-entry">
            <label class="ti_cms_labelHide">
                <span>Phone</span>
                <input class="required-entry ti_checkout_info" type="text" value="Phone" onfocus="if(this.value=='Phone')this.value='';" onblur="if(this.value=='')this.value='Phone';">
            </label>
        </div>
        <div class="one_half">
            <label class="ti_cms_labelHide">
                <span>Fax</span>
                <input class="ti_checkout_info" type="text" value="Fax" onfocus="if(this.value=='Fax')this.value='';" onblur="if(this.value=='')this.value='Fax';">
            </label>
        </div>
        <div class="one_half">
            <!--ti_checkout_optionChecked shows by default-->
            <label class="altTxt btcf"><input type="checkbox" checked="checked"><span><span class="ti_small_text">Save your information for future orders</span></span></label>
            <!--if ti_checkout_optionUnChecked then these two inputs do not display-->
            <div class="ti-required-entry ti_checkout_half">
                <label class="ti_cms_labelHide">
                    <span>Password</span>
                    <input class="required-entry" type="text" value="Password" onfocus="if(this.value=='Password')this.value='';" onblur="if(this.value=='')this.value='Password';">
                </label>
            </div>
            <div class="ti-required-entry ti_checkout_half">
                <label class="ti_cms_labelHide">
                    <span>Password (retype)</span>
                    <input class="required-entry" type="text" value="Password (retype)" onfocus="if(this.value=='Password (retype)')this.value='';" onblur="if(this.value=='')this.value='Password (retype)';">
                </label>
            </div>
        </div>
        <div class="one_half">
            <label class="altTxt btcf"><input type="checkbox" checked="checked"><span><span class="ti_small_text">Sign up for TomatoInk's bi-weekly email deals</span></span></label>
            <!--if ti_checkout_optionChecked then shipping info displays-->
            <label class="altTxt btcf"><input type="checkbox" checked="checked"><span><span class="ti_small_text">Ship to a different address</span></span></label>
        </div>
    </div>
    <!--end billing info-->
    <div id="ti_checkout_ShipInfo" class="btcf">
        <h2 class="lgTxt ti_headerH1">Shipping Information</h2>
        <div class="one_half ti-required-entry">
            <label class="ti_cms_labelHide">
                <span>First Name</span>
                <input class="required-entry ti_checkout_info" type="text" value="First Name"onfocus="if(this.value=='First Name')this.value='';" onblur="if(this.value=='')this.value='First Name';"/>
            </label>
        </div>
        <div class="one_half ti-required-entry">
            <label class="ti_cms_labelHide">
                <span>Last Name</span>
                <input class="required-entry ti_checkout_info" type="text" value="Last Name"onfocus="if(this.value=='Last Name')this.value='';" onblur="if(this.value=='')this.value='Last Name';">
            </label>
        </div>
        <div class="one_half ti-required-entry">
            <label class="ti_cms_labelHide">
                <span>Email</span>
                <input class="required-entry ti_checkout_info" type="text" value="Email"onfocus="if(this.value=='Email')this.value='';" onblur="if(this.value=='')this.value='Email';">
            </label>
        </div>
        <div class="one_half">
            <label class="ti_cms_labelHide">
                <span>Company</span>
                <input class="ti_checkout_info" type="text" value="Company" onfocus="if(this.value=='Company')this.value='';" onblur="if(this.value=='')this.value='Company';">
            </label>
        </div>
        <div class="one ti-required-entry">
            <label class="ti_cms_labelHide">
                <span>Address line 1</span>
                <input class="required-entry ti_checkout_info" type="text" value="Address" onfocus="if(this.value=='Address')this.value='';" onblur="if(this.value=='')this.value='Address';">
            </label>
        </div>
        <div class="one">
            <label class="ti_cms_labelHide">
                <span>Address line 2</span>
                <input class="ti_checkout_info" type="text">
            </label>
        </div>
        <div class="one_half ti-required-entry">
            <label class="ti_cms_labelHide">
                <span>City</span>
                <input class="required-entry ti_checkout_info" type="text" value="City" onfocus="if(this.value=='City')this.value='';" onblur="if(this.value=='')this.value='City';">
            </label>
        </div>
        <div class="one_half ti-required-entry">
            <label class="ti_cms_labelHide">
                <span>Zip Code</span>
                <input class="required-entry ti_checkout_info" type="text" value="Zip" onfocus="if(this.value=='Zip')this.value='';" onblur="if(this.value=='')this.value='Zip';">
            </label>
        </div>
        <div class="one_half ti-required-entry">
            <label class="ti_cms_labelHide">
                <span>Phone</span>
                <input class="required-entry ti_checkout_info" type="text" value="Phone" onfocus="if(this.value=='Phone')this.value='';" onblur="if(this.value=='')this.value='Phone';">
            </label>
        </div>
        <div class="one_half">
            <label class="ti_cms_labelHide">
                <span>Fax</span>
                <input class="ti_checkout_info" type="text" value="Fax" onfocus="if(this.value=='Fax')this.value='';" onblur="if(this.value=='')this.value='Fax';">
            </label>
        </div>
    </div>
</div>
<div class="one btcf">
    <div class="ti_cms_block_headerBar-green">
        <h2 class="white ti_headerH1" id="ti_checkoutStep2"><span class="ti_checkoutStep">2</span> Shipping</h2>
    </div>
    <div class="ti_cms_gradient_block btcf">
        <div class="ti_block_inner">
            <div class="ti_select_barContainer">
                <select id="">
                    <option value>Method</option>
                    <option value>Ground</option>
                    <option value>UPS 24 hour shipping</option>
                </select>
            </div>
        </div>
    </div>
</div>
<div class="one btcf">
    <div class="ti_cms_block_headerBar-green">
        <h2 class="white ti_headerH1" id="ti_checkoutStep3"><span class="ti_checkoutStep">3</span> Payment</h2>
    </div>
    <div class="ti_cms_gradient_block btcf">
        <div class="one_third ti_block_inner">
            <ul class="ti_checkout_list">
                <li><label>
                    <input type="radio"><div class="ti_select_barContainer">
                        <select id="">
                            <option value>Saved method</option>
                            <option value>Credit Card 1</option>
                            <option value>Credit Card 2</option>
                        </select>
                    </div></label>
                </li>
                <!--when radio is selected, lose class="ltWeight"-->
                <li>
                    <label class="lgTxt ltWeight"><input type="radio"><span class="ti_checkout_credit paypal"></span><span><span class="ti_small_text">Paypal</span></span></label>
                </li>
                <li>
                    <label class="lgTxt ltWeight"><input type="radio"><span class="ti_checkout_credit google"></span><span><span class="ti_small_text">Google Wallet</span></span></label>
                </li>
                <li>
                    <label class="lgTxt ltWeight"><input type="radio"><span><span class="ti_small_text">Credit Card</span></span></label>
                </li>
            </ul>
        </div>
        <div class="two_third ti_block_inner"  style="display:none;"><!--this hides when user selects "Credit Card"-->
            <h2 class="ltWeight text_center lgTxt"><span class="icon-lock ti_checkout_secure"></span><br>All payments are secure.</h2>
        </div>
        <div class="one_third ti_block_inner"><!--this displays when user selects "Credit Card"-->
            <p><span class="ti_checkout_credit mastercard"></span> <span class="ti_checkout_credit visa"></span> <span class="ti_checkout_credit discover"></span> <span class="ti_checkout_credit amex"></span></p>
            <div class="ti-required-entry">
                <label class="ti_cms_labelHide">
                    <span>Name on card</span>
                    <input class="required-entry ti_checkout_info" type="text" value="Name on card" onfocus="if(this.value=='Name on card')this.value='';" onblur="if(this.value=='')this.value='Name on card';">
                </label>
            </div>
            <div class="ti-required-entry">
                <label class="ti_cms_labelHide">
                    <span>Card Number</span>
                    <input class="required-entry ti_checkout_info" type="text" value="Card number" onfocus="if(this.value=='Card number')this.value='';" onblur="if(this.value=='')this.value='Card number';">
                </label>
            </div>
        </div>
        <div class="one_third ti_block_inner"><!--this displays when user selects "Credit Card"-->
            <div class="one">
                <div class="ti_checkout_half ti-required-entry">
                    <div class="ti_select_barContainer">
                        <label class="ti_cms_labelHide">
                            <span>Month</span>
                            <select id="">
                                <option value>Month</option>
                                <option value>Jan</option>
                                <option value>Feb</option>
                                <option value>March</option>
                                <option value>Apr</option>
                                <option value>May</option>
                                <option value>June</option>
                                <option value>July</option>
                                <option value>Aug</option>
                                <option value>Sep</option>
                                <option value>Oct</option>
                                <option value>Nov</option>
                                <option value>Dec</option>
                            </select>
                        </label>
                    </div>
                </div>
                <div class="ti_checkout_half ti-required-entry">
                    <label class="ti_cms_labelHide">
                        <span>Year</span>
                        <input class="required-entry ti_checkout_info" type="text" value="Year" onfocus="if(this.value=='Year')this.value='';" onblur="if(this.value=='')this.value='Year';">
                    </label>
                </div>
            </div>
            <div class="one ti-required-entry">
                <label class="ti_cms_labelHide">
                    <span>CCV</span>
                    <input class="required-entry ti_checkout_info ti_checkout_ccv" type="text" value="CCV" onfocus="if(this.value=='CCV')this.value='';" onblur="if(this.value=='')this.value='CCV';"> 
                    <ul id="ti_checkout_ccv">
                        <li><a rel="nofollow">What's this?</a></li>
                    </ul>
                </label>
            </div>
            <div class="one">
                <label class="altTxt"><input type="checkbox" class="ti_checkout_optionChecked"><span><span class="ti_small_text">Save this method for future orders</span></span></label>
            </div>
        </div>
    </div>
</div>
<div class="one btcf">
    <div class="ti_cms_block_headerBar-green">
        <h2 class="white ti_headerH1" id="ti_checkoutStep4"><span class="ti_checkoutStep">4</span> Additional Info (Optional)</h2>
    </div>
    <div class="ti_cms_gradient_block btcf">
        <div class="one_third ti_block_inner">
            <div class="ti_select_barContainer">
                <select id="">
                    <option value>How'd you find us?</option>
                    <option value>Google</option>
                    <option value>Friend</option>
                </select>
            </div>
        </div>
        <div class="two_third ti_block_inner">
            <textarea placeholder="We'd love to hear from you!" spellcheck="true" rows="3" class="ti_checkout_comments"></textarea>
        </div>
    </div>
</div>
<div class="one btcf">
    <div class="ti_cms_block_headerBar-green">
        <h2 class="white ti_headerH1" id="ti_checkoutStep5"><span class="ti_checkoutStep">5</span> Review Order</h2>
    </div>
    <!--this is where the table goes. let's throw it in here and I can review before adding additional elements.-->
</div>

<!-- end Megan HTML -->

<div class="page-title checkout-title">
    <h1><?php echo Mage::getStoreConfig('firecheckout/general/title') ?></h1>
    <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()) : ?>
    <p class="firecheckout-login-wrapper">
        <a href="<?php echo $this->getUrl('customer/account/login') ?>" class="firecheckout-login">
            <span><span><?php echo $this->__('Already registered? Login into your account') ?></span></span>
        </a>
    </p>
    <?php endif; ?>
</div>

<?php
    echo $this->getMessagesBlock()->getGroupedHtml();
    $this->getMessagesBlock()->getMessageCollection()->clear();
?>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/tm/firecheckout.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/tm/firecheckout-compatibility.js') ?>"></script>
<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<script type="text/javascript">
//<![CDATA[
    FireCheckout.prototype.ajax = {
    <?php
        $json = '';
        foreach (Mage::getStoreConfig('firecheckout/ajax_update') as $key => $value):
            $json .= $key . ':' . (int)$value . ",\n";
        endforeach;
        echo $this->htmlEscape(substr($json, 0, -2));
    ?>
    };
//]]>
</script>

<form action="" id="firecheckout-form" method="post">
<?php
if ($blockId = Mage::getStoreConfig('firecheckout/additional_content/top')) :
    echo $this->getLayout()->createBlock('cms/block')->setBlockId($blockId)->toHtml();
endif;
?>
<div class="clearer"></div>

<?php $layout = Mage::getStoreConfig('firecheckout/general/layout'); ?>
<div class="<?php echo $layout ?> firecheckout-set">
    <div class="col-1">
        <?php echo $this->getChildHtml('billing.address') ?>
        <?php echo $this->getChildHtml('shipping.address') ?>
    </div>

    <div class="col-2">

        <?php if ('col2-set' === $layout) : ?>
            <div class="col2-set">
                <div class="col-1">
        <?php endif; ?>

        <?php echo $this->getChildHtml('shipping.method') ?>

        <?php if ('col2-set' === $layout) : ?>
                </div>
                <div class="col-2">
        <?php endif; ?>

        <?php echo $this->getChildHtml('payment.method') ?>
        <?php if ($j2tRewardPoints = $this->getLayout()->getBlock('checkout_cart_coupon_normal')): // rewardpoints extension override standard discount block too ?>
            <div id="checkout-coupon-discount-load">
                <?php echo $j2tRewardPoints->toHtml(); ?>
            </div>
        <?php else: ?>
            <div id="checkout-coupon-discount-load">
                <?php echo $this->getChildHtml('coupon') ?>
            </div>
        <?php endif; ?>
        <div id="checkout-giftcard-load">
            <?php echo $this->getChildHtml('giftcard') ?>
        </div>

        <?php if ('col2-set' === $layout) : ?>
                </div>
            </div>
        <?php endif; ?>

    <?php if ('col3-set' === $layout) : ?>
    </div>
    <div class="col-3">
    <?php endif; ?>

        <?php echo $this->getChildHtml('review') ?>

    </div>
</div>

<?php
if ($blockId = Mage::getStoreConfig('firecheckout/additional_content/bottom')) :
    echo $this->getLayout()->createBlock('cms/block')->setBlockId($blockId)->toHtml();
endif;
?>
<div class="clearer"></div>
</form>

<?php echo $this->getChildHtml('customer.login') ?>
<?php echo $this->getChildHtml('customer.forgot') ?>
<?php if (Mage::helper('core')->isModuleOutputEnabled('Mage_Persistent')) : ?>
    <?php echo $this->getChildHtml('persistent.login') ?>
<?php endif; ?>
<div id="checkout-centinel-iframe-load" style="display: none;"></div>
<div id="checkout-paypaliframe-load" class="authentication" style="display: none;"></div>
<div id="checkout-sagepay-iframe-load"></div>
<form id="co-payment-form" method="post" action=""></form>

<script type="text/javascript">
//<![CDATA[
    <?php $_isSecure = $this->getRequest()->isSecure(); ?>
    var checkout = new FireCheckout('firecheckout-form', {
        success         : '<?php echo $this->getUrl('checkout/onepage/success',              array('_secure'=>$_isSecure)) ?>',
        save            : '<?php echo $this->getUrl('firecheckout/index/saveOrder',          array('_secure'=>$_isSecure, 'form_key' => Mage::getSingleton('core/session')->getFormKey())) ?>',
        billing_address : '<?php echo $this->getUrl('firecheckout/index/saveBilling',        array('_secure'=>$_isSecure)) ?>',
        shipping_address: '<?php echo $this->getUrl('firecheckout/index/saveShipping',       array('_secure'=>$_isSecure)) ?>',
        shipping_method : '<?php echo $this->getUrl('firecheckout/index/saveShippingMethod', array('_secure'=>$_isSecure)) ?>',
        payment_method  : '<?php echo $this->getUrl('firecheckout/index/savePayment',        array('_secure'=>$_isSecure)) ?>',
        coupon          : '<?php echo $this->getUrl('firecheckout/index/saveCoupon',         array('_secure'=>$_isSecure)) ?>',
        giftcard        : '<?php echo $this->getUrl('firecheckout/index/saveGiftcard',       array('_secure'=>$_isSecure)) ?>',
        paymentdata     : '<?php echo $this->getUrl('firecheckout/index/savePaymentData',    array('_secure'=>$_isSecure)) ?>',
        presave         : '<?php echo $this->getUrl('firecheckout/index/preSaveOrder',       array('_secure'=>$_isSecure)) ?>',
        shopping_cart   : '<?php echo $this->getUrl('firecheckout/index/saveCart',           array('_secure'=>$_isSecure)) ?>',
        failure         : '<?php echo $this->getUrl('checkout/cart') ?>'
    }, {
        acceptAgreementText: "<?php echo $this->__('Please agree to all the terms and conditions before placing the order.') ?>",
        spinnerText        : "<?php echo $this->__('Please wait...') ?>",
        productRemoveConfirm: "<?php echo $this->__('Are you sure you would like to remove this item from the shopping cart?') ?>"
    });
    var fireCart = new FireCheckout.Cart({
        descriptionLength: <?php echo (int)Mage::getStoreConfig('firecheckout/shopping_cart/short_description_length') ?>
    });

    <?php if (Mage::getStoreConfig('firecheckout/general/order_review')) : ?>
    var reviewInfo;
    function initOrderReview() {
        reviewInfo = new FireCheckout.OrderReview({
            changeText: "<?php echo $this->__('Change') ?>"
        });
    }
    if (Prototype.Browser.IE) {
        document.observe("dom:loaded", function() { //KB927917 fix
            initOrderReview();
        });
    } else {
        initOrderReview();
    }
    <?php endif; ?>

    document.observe("dom:loaded", function() {
        var triggers = {
            login: {
                el    : $$('.firecheckout-login'),
                event : 'click',
                window: $('firecheckout-login-window'),
                size: {
                    maxWidth: 300
                }
            },
            forgot: {
                el    : $$('.firecheckout-forgot'),
                event : 'click',
                window: $('firecheckout-forgot-window'),
                size: {
                    maxWidth: 300
                }
            }
        };
        $$('.checkout-agreements .agree a').each(function(el) {
            triggers[el.className] = {
                el    : $$('.' + el.className),
                event : 'click',
                window: $(el.className + '-window'),
                actionbar: {
                    html    : '<a href="javascript:void(0)" class="btn-agree" id="' + el.className + '-button" title="' + el.innerHTML + '">' + el.innerHTML + '</a>',
                    el      : el.className + '-button',
                    event   : 'click',
                    callback: function(e, id) {
                        if (typeof event != 'undefined') { // ie9 fix
                            event.preventDefault ? event.preventDefault() : event.returnValue = false;
                        }
                        e.stop();
                        $(id).checked = 'checked';
                        this.hide();
                    }
                }
            };
        });
        firecheckoutWindow = new FireCheckout.Window({
            triggers: triggers
        });
    });
//]]>
</script>