<?php if (Mage::getSingleton('customer/session')->isLoggedIn()): return; endif; ?>
<div id="firecheckout-login-window" style="display: none;">
    <div class="page-title">
        <h3><?php echo $this->__('Login to your Account') ?></h3>
    </div>
    <form action="<?php echo $this->getUrl('*/*/login', array('_secure'=>(!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on'))) ?>" method="post" id="firecheckout-login-form">
        <div class="content">
            <ul class="form-list">
                <li>
                    <label for="email" class="required ti-required-entry ti_cms_labelHide"><span><?php echo $this->__('Email Address') ?></span></label>
                    <div class="input-box">
                        <input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" placeholder="Email Address" />
                    </div>
                </li>
                <li>
                    <label for="pass" class="required ti-required-entry ti_cms_labelHide"><span><?php echo $this->__('Password') ?></span></label>
                    <div class="input-box">
                        <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" placeholder="Password" />
                    </div>
                </li>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
            </ul>
        </div>
        <div class="buttons-set">
            
            <button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button><br>
            <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="firecheckout-forgot"><?php echo $this->__('Forgot Your Password?') ?></a>
            <span class="please-wait" id="login-please-wait" style="display:none;">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt=""/>
            </span>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var loginForm = new VarienForm('firecheckout-login-form', true);
    //]]>
    </script>
</div>