<div class="knowledgebase-block block">
    <div class="knowledgebase-block-title block-title">
        <strong><span><?php echo $this->__('Categories');?></span></strong>
    </div>
    <div class="knowledgebase-block-content block-content">
        <?php $collection = $this->getCollection();
        if($collection && count($collection) ): ?>
            <ul>
                <?php foreach ($collection as $_category):?>
                <li>
                    <h4>
                        <a href="<?php echo $this->getCategoryUrl(
                            $_category->getIdentifier()
                        )?>"><?php echo $_category->getName() ?></a>&nbsp;
                    </h4>
                    <ul class="knowledge-articles-list">
                        <?php foreach ($_category->getFaqs() as $_faq):?>
                        <li>
                            <a href="<?php echo $this->getArticleUrl(
                                $_faq->getIdentifier()
                            )?>"><?php echo $_faq->getTitle() ?></a>&nbsp;
                        </li>
                        <?php endforeach; ?>
                    </ul>
                </li>
                <?php endforeach; ?>
            </ul>

        <?php else: ?>
            <p><?php echo $this->__('You have no categories.') ?></p>
        <?php endif; ?>
    </div>
</div>