<div class="ti_checkoutStep" id="ti_cartlogin_close">
    <a href="#"><p class="ti_orange_head">X</p></a>
</div>
<h2><?php echo $this->__('Customer Login') ?></h2>

<form action="<?php echo Mage::getUrl('productselector/cartlogin/index',array('_secure'=>true)) ?>" method="post">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <div class="block-content">
        <p class="altTxt" id="ti_cart_popup_error_msg">Invalid User Email or Password </p>
        <p><a href="#" id="ti_cart_popup_forget_pass">Forget Password?</p>
        <div class="full ti-required-entry">
            <label for="login-email" class="ti_cms_labelHide"><span><?php echo $this->__('Email Address') ?></span></label>
            <input type="email" name="login[username]" class="required-entry width100" id="login-email" required="required" value="<?php echo $this->__('Email') ?>" onfocus="if(this.value=='<?php echo $this->__('Email') ?>')this.value='';" onblur="if(this.value=='')this.value='<?php echo $this->__('Email') ?>';"/>
        </div>
        <div class="full ti-required-entry">
            <label for="login-password" class="ti_cms_labelHide"><span><?php echo $this->__('Password') ?></span></label>
            <input type="password" name="login[password]" value="<?php echo $this->__('Password') ?>" onfocus="if(this.value=='<?php echo $this->__('Password') ?>')this.value='';" onblur="if(this.value=='')this.value='<?php echo $this->__('Password') ?>';" class="required-entry width100" id="login-password" required="required" />
        </div>
        <div class="actions">
            <button type="submit" class="ti_button one_half"><span><span><?php echo $this->__('Login') ?></span></span></button>
            <a href="" id="ti_show_register_info" class="ti_button ti_altBtn one_half text_center"><?php echo $this->__('Create an Account') ?></a>
        </div>
    </div>
</form>



<!--<div class="ti_cms_block_headerBar-green text_center">
    <div class="ti_checkoutStep" id="ti_cartlogin_close"><a href="#" class="ti_txt_dec_none"><p class="ti_orange_head">X</p></a></div>
    <h2 class="white ti_headerH1 ti_top_margin_hide"><span><?php /*echo $this->__('Customer Login') */?></span></h2>
</div>
<form action="<?php /*echo Mage::getUrl('productselector/cartlogin/index',array('_secure'=>true)) */?>" method="post">
    <?php /*echo $this->getBlockHtml('formkey'); */?>
    <div class="block-content text_center">
        <h2 class="ti_green_head" id="ti_cart_popup_error_msg">Invalid User Email or Password </h2>
        <a href="#" id="ti_cart_popup_forget_pass" ><h2 class="ti_orange_head" >Forget Password?</h2></a>
        <h2 class="ti_orange_head"><em> * </em><?php /*echo $this->__('Email Address') */?></h2><input type="email" name="login[username]" class="required-entry" id="login-email" required="required" placeholder="<?php /*echo $this->__('Email') */?>" /><br/>
        <h2 class="ti_orange_head"><em> * </em><?php /*echo $this->__('Password') */?></h2><input type="password" name="login[password]" placeholder="<?php /*echo $this->__('Password') */?>" class="required-entry" id="login-password" required="required" />
        <div class="actions">
            <button type="submit" class="ti_button"><span><span><?php /*echo $this->__('Login') */?></span></span></button>
        </div>
        <div class="actions">
            <a href="" id="ti_show_register_info" class="ti_button ti_txt_dec_none"><?php /*echo $this->__('Create an Account') */?></a>
        </div>
    </div>
</form>
-->