<div class="ti_cms_block_headerBar-green text_center">
        <h2 class="white ti_headerH1 ti_top_margin_hide"><span><?php echo $this->__('Customer Login') ?></span></h2>
</div>
<form action="<?php echo Mage::getUrl('productselector/cartlogin/index',array('_secure'=>true)) ?>" method="post">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <div class="block-content text_center">
        <h1 class="ti_orange_head">Email</h2><input type="email" name="login[username]" class="required-entry" id="login-email" required="required" placeholder="Email" /><br/>
        <h1 class="ti_orange_head">Password</h2><input type="password" name="login[password]" placeholder="Password" class="required-entry" id="login-password" required="required" />
        <div class="actions">
            <button type="submit" class="ti_button"><span><span><?php echo $this->__('Login') ?></span></span></button>
        </div>
    </div>
</form>