<div class="ti_ink_selector_holder">
	
	<h1 class="ti_green_head">Ink Selector Tools</h1>
	<p>Please Select your printer Brand/Series/Model for your Ink / Cartridge </p>
	<div style="width:100%;position:relative;float:left">
			
            <div class="ti_ink_selector_div">
				<div id="ti_ajax_loading_ink"><img src="<?php echo $this->getSkinUrl('images/loading.gif') ?>" /></div>
				<div id="ti_ajax_loading_series"><img src="<?php echo $this->getSkinUrl('images/loading.gif') ?>" /></div>
                <h3>Choose Printer Brand</h3>
                <select name="" id="ti_brand_selector" class="ti_select_text">
                    <option value="">select the brand</option>
                    <?php
                    $category_model = Mage::getModel('catalog/category')->load(2);
					$subcategoryIds = $category_model->getChildren();
					$subCatIds = explode(',',$subcategoryIds);	
					$collection = Mage::getResourceModel('catalog/category_collection')->addFieldToFilter('entity_id',$subCatIds)->addAttributeToSelect(array('name','entity_id'))->load();
					
					foreach($collection as $item){
				
						echo '<option value="'.$item->entity_id.'">'.$item->name.'</option>';
					}

                    ?>
                </select>
            </div>
            <div class="ti_ink_selector_div">
                <h3>Choose Printer Series</h3>
                <select disabled="" name="" id="ti_series_selector" class="ti_select_text">
                    <option value="0" selected="">select your printer series</option>
                </select>
            </div>
            <div class="ti_ink_selector_div">
                <h3>Choose Model/Cartridge</h3>

                <select disabled="" name="" id="ti_cartridge_selector" class="ti_select_text">
                    <option value="" selected="">select your printer cartridge</option>
                </select>
            </div>


	</div>
</div>
<script src="http://code.jquery.com/jquery-1.8.3.js" type="text/javascript"></script>
<script>
jQuery.noConflict();
jQuery(function(){
    jQuery("#ti_brand_selector").change(function() {
	    document.getElementById("ti_series_selector").disabled=true;
		document.getElementById("ti_cartridge_selector").disabled=true;
		document.getElementById("ti_brand_selector").disabled=true;
        var dataString = jQuery(this).val();
		jQuery.post("productselector/ajax/index",{id : dataString},function(data){
			jQuery('#ti_series_selector').html(data);
		});
		/*jQuery.post("productselector/ink/simple",{id : dataString},function(data){
			jQuery('#ti_cartridge_selector').html(data);
		});*/
        jQuery("#ti_ajax_loading_ink").show();
        jQuery(".ti_ink_selector_holder").fadeTo('slow',.4);
        new Ajax.Request("productselector/ink/simple", {
            method: "post",
            parameters: {
              id : dataString
            },
            cache: false,
            onSuccess: function(transport) {
				jQuery('#ti_cartridge_selector').html(transport.responseText);
				jQuery("#ti_ajax_loading_ink").hide();
				jQuery(".ti_ink_selector_holder").fadeTo('slow',1.0);
				document.getElementById("ti_series_selector").disabled=false;
				document.getElementById("ti_cartridge_selector").disabled=false;
				document.getElementById("ti_brand_selector").disabled=false;
            }
        });
    });
    jQuery("#ti_series_selector").change(function() {

        var dataString = jQuery(this).val();
		
        if(dataString > 0){
			document.getElementById("ti_series_selector").disabled=true;
			document.getElementById("ti_cartridge_selector").disabled=true;
			document.getElementById("ti_brand_selector").disabled=true;
            jQuery("#ti_ajax_loading_series").show();
			jQuery(".ti_ink_selector_holder").fadeTo('slow',.4);
            new Ajax.Request( "productselector/ink/index", {
                method: "post",
                parameters: {
                  id : dataString
                },
                cache: false,
                onSuccess: function(transport) {
					jQuery('#ti_cartridge_selector').html(transport.responseText);
					jQuery("#ti_ajax_loading_series").hide();
					jQuery(".ti_ink_selector_holder").fadeTo('slow',1.0);
					document.getElementById("ti_series_selector").disabled=false;
					document.getElementById("ti_cartridge_selector").disabled=false;
					document.getElementById("ti_brand_selector").disabled=false;
                }
            });
        }
    });

    jQuery("#ti_cartridge_selector").change(function() {
        var id=jQuery(this).val();
        window.open("https://www.866ink.com/magentoEE/index.php/catalog/product/view/id/"+ id, "_self");
    });
});

</script>