<!--<div class="ti_ink_selector_holder">-->
	
	<h2 class="ti_green_head ti_headerH1">Ink Search</h2>
	<!--<p>Please Select your printer Brand/Series/Model for your Ink / Cartridge </p>
	<div style="width:100%;position:relative;float:left">
		<div class="ti_ink_selector_div">-->
        <div class="ti_select_barContainerBorder btcf">
            <div class="ti_select_barContainer btcf">    

    			<div id="ti_ajax_loading_ink"><img src="<?php echo $this->getSkinUrl('images/ti_loading_small.gif') ?>"/></div>
    			<div id="ti_ajax_loading_series"><img src="<?php echo $this->getSkinUrl('images/ti_loading_small.gif') ?>"/></div>
               <!--<h3>Choose Printer Brand</h3>-->
                <select id="topCategoriesLeft" name="topCategoriesLeft">
                    <option value="">1. Choose Your Printer Brand</option>
                    <?php
                    $category_model = Mage::getModel('catalog/category')->load(2);
    				$subcategoryIds = $category_model->getChildren();
    				$subCatIds = explode(',',$subcategoryIds);	
    				$collection = Mage::getResourceModel('catalog/category_collection')->addAttributeToFilter('is_active', 1)->addFieldToFilter('entity_id',$subCatIds)->addAttributeToSelect(array('name','entity_id'))->load();
    				
    				foreach($collection as $item){
    			
    					echo '<option value="'.$item->entity_id.'">'.$item->name.'</option>';
    				}

                    ?>
                </select>
            </div>
        </div>
        <!--<div class="ti_ink_selector_div">-->
        <div class="ti_select_barContainerBorder btcf">
            <div class="ti_select_barContainer btcf">
                <!--<h3>Choose Printer Series</h3>-->
                <select name="subCategoriesLeft" id="subCategoriesLeft">
                    <option value="">2. Choose Your Printer Series</option>
                </select>
            </div>
        </div>
        <!--<div class="ti_ink_selector_div">-->
        <div class="ti_select_barContainerBorder btcf">
            <div class="ti_select_barContainer btcf">
                <!--<h3>Choose Model/Cartridge</h3>-->

                <select name="groupedProductsLeft" id="groupedProductsLeft">
                    <option value="">3. Choose Your Printer Model</option>
                </select>
            </div>
        </div>


	<!--</div>
</div>-->
<script type="text/javascript">
    //<![CDATA[
    function reset_options() {
        document.getElementById('topCategoriesLeft').selectedIndex = 0;
        return true;
    }
    window.onload=reset_options;

    var catalogUrl = 'http://www.866ink.com/magentoEE/productselector/ajax/index';

    var urlMappingTable = {};
    Event.observe($('topCategoriesLeft'), 'change', function() {
        if (this.value != '') {
            resetShoppingEasyLeft($('subCategoriesLeft'));
            resetShoppingEasyLeft($('groupedProductsLeft'));
            new Ajax.Request(catalogUrl + '?id=' + this.value, {
                method: 'get',
                asynchronous: false,
                onSuccess: function(transport) {
                    var data = transport.responseText.evalJSON();
                    if (data) {
                        addDataToShippingEasyLeft(data);
                    }
                }
            })
        }
    });

    Event.observe($('subCategoriesLeft'), 'change', function() {
        if (this.value != '') {
            if (urlMappingTable[this.value]) {

                var sub = this;
                var data = urlMappingTable[this.value];
                var prod = $('groupedProductsLeft');
                resetShoppingEasyLeft(prod);
                for (var i in data) {
                    if (data[i]) {
                        var opt = document.createElement('option');
                        opt.value = data[i].url;
                        opt.text = data[i].name;
                        try {
                            prod.add(opt, null);
                        } catch (ex) {
                            prod.add(opt);
                        }
                    }
                }
            }
        }
        sortOptions('groupedProductsLeft');
    });

    Event.observe($('groupedProductsLeft'), 'change', function() {
        if (this.value != '') {
            document.location = this.value;
        }
    });

    function resetShoppingEasyLeft(el) {
        if (el != undefined) {
            for (i = el.options.length - 1; i > 0; i--) {
                if (i > 0) {
                    el.remove(i);
                }
            }
        }
    }

    function addDataToShippingEasyLeft(data)
    {
        urlMappingTable = {};
        var sub = $('subCategoriesLeft');
        sub.disabled = true;
        if (data) {
            for (var i in data) {
                var opt = document.createElement('option');
                opt.value = i;
                opt.text = data[i].name;
                if (data[i].sub) {
                    try {
                        sub.add(opt, null);
                    } catch (ex) {
                        sub.add(opt);
                    }
                    var map = data[i].sub;
                    urlMappingTable[i] = {};
                    for (var j in map) {
                        if (map[j].id)
                            urlMappingTable[i][map[j].id] = map[j];
                    }

                }
            }
        }
        sub.disabled = false;
        sortOptions('subCategoriesLeft');
    }

    function sortOptions(name)
    {
        var cl = document.getElementById(name);
        var clTexts = new Array();

        for(i = 1; i < cl.length; i++)
        {
            clTexts[i-1] =
                cl.options[i].text.toUpperCase() + "," +
                    cl.options[i].text + "," +
                    cl.options[i].value;

        }
        clTexts.sort();
        for(i = 1; i < cl.length; i++)
        {
            var parts = clTexts[i-1].split(',');

            cl.options[i].text = parts[1];
            cl.options[i].value = parts[2];
        }
        for (var i = 0; i < cl.length; i++){
            if (cl.options[i].text.match(/Other/)){
                var msg1 = cl.options[i];
                cl.removeChild(cl.options[i]);
                cl.appendChild(msg1);
            }
        }
    }
    //]]>
</script>