<div class="ti_block_inner">

<?php
$coreResource = Mage::getSingleton('core/resource');
$conn = $coreResource->getConnection('core_read');
$cart = Mage::getModel('checkout/cart')->getQuote();
$total_num = round($cart->getItemsQty());
if ($total_num == "") $total_num=0;

$grandtotal = $cart->getSubtotal();

$select = $conn->select()
    ->from($coreResource->getTableName('sales_flat_quote_item'),array('product_id'))
    ->where('parent_item_id IS NULL')
    ->where('quote_id = ?',$cart->getId());
$cartItems = $conn->fetchCol($select); //this for bundle otherwise all product under bundle will show in cart

echo "<h2> Total Items in Cart : ".$total_num."   <br><strong class='altTxt'>Sub Total: $" . round($grandtotal,2) . "</strong></h2> <span class='ti_close_popup'><a href='#' class='ti_checkoutStep_close altTxt'>X</a></span>";

$quote = Mage::getModel('sales/quote')->load($cart->getId());
$cartitem = Mage::getModel('sales/quote_item')
	->getCollection()
	->setQuote($quote)
	->addOrder('updated_at', 'desc');
 
foreach ($cartitem as $item) {
    $product = $item->getProduct();
    if(in_array($product->getId(),$cartItems) and $item->getPrice() > 0 ) //this for bundle otherwise all product under bundle will show in cart
        echo "<div class='one_fifth'><a href='" . $product->getProductUrl() . "'><img class='block_center' src='" . $this->helper('catalog/image')->init( $product, 'small_image')->resize(75) . "'></img></a></div><div class='two_fifth'><a href='" . $product->getProductUrl() . "'><p class='ti_product_blockName'>" . $product->getName() . "</p></a></div><div class='one_fifth text_center'><p>".$item->getQty()."</p></div><div class='one_fifth'><p>$".$item->getQty() * $item->getPrice()."</p></div><div class='ti_cms_separator'></div>";
    

}
echo "<div class='text_center'><a class='ti_button' href='" . $this->getUrl('') . "checkout/cart/'><strong>Checkout</strong></a>";
//echo "<a class='ti_button ti_altBtn' href='".$this->getContinueShoppingUrl()."' ><strong>Continue Shopping</strong></a></div>";
?><a class="ti_button ti_altBtn" href="#" id="ti_continue_shopping"><strong>Continue Shopping</strong></a></div>

</div>
<script>
    jQuery('.ti_close_popup').click(function(e){
        e.preventDefault();
        jQuery('#show_cart').hide("slow");
        jQuery('#ti_hide_body_div').hide();
         e.stopPropagation();
    });
    jQuery('#ti_continue_shopping').click(function(e){
        e.preventDefault();
        jQuery('#show_cart').hide("slow");
        jQuery('#ti_hide_body_div').hide();
        e.stopPropagation();
    });
    
</script>