<head>
    <title>TomatoInk Chat Page</title>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/ti-chat.css') ?>" />
    <link rel="shortcut icon" href="<?php echo $this->getSkinUrl('images/ti-chat/favicon.png') ?>">

</head>

<body style="overflow:hidden">
    <div style="width:100%; height:100%">
        <div class="wrapper">
            <div class="header">
                <div class="logo">
                    <img src="<?php echo $this->getSkinUrl('images/ti-chat/logo.jpg') ?>" border="0">
                </div>
                <div class="right">
                    <img src="<?php echo $this->getSkinUrl('images/ti-chat/right.jpg') ?>" border="0">
                </div>

            </div>
            <div class="container">
                <div class="top_container">
                    <div class="chat_welcome">
                        <h2 class="center">Welcome to TomatoInk Live Chat Support</h2>
                        <!-- <p>A live chat representative is standing by to provide assistance. So that we can better assist you, please provide some information about your reason for chatting with us today. </p> -->
                    </div>
                    <div class="chat_container">
                        <iframe src="https://messenger.providesupport.com/messenger/lubu12.html" frameborder="0" scrolling="no" >
            Your browser does not support IFrames.
                        </iframe>
                    </div>
                </div>
                <div class="bottom_container">
                    <div class="left_bottom">
                        <div class="left_bottom_header"><h3 class="center">1 Year Warranty</h3>
                        </div>
                        <div class="left_bottom_img">
                            <img src="<?php echo $this->getSkinUrl('images/ti-chat/left_icons.png') ?>" />
                            <p style="padding-right:20px" class="left_bottom_img_res" >Every item you purchase is backed with our 100% satisfaction 1 year money back guarantee</p>
                        </div>

                    </div>
                    <div class="right_bottom">
                        <div class="left_bottom_header"><h3 class="center">Fast and Free Shipping</h3>

                        </div>
                        <div class="left_bottom_img">
                            <img src="<?php echo $this->getSkinUrl('images/ti-chat/right_icons.png') ?>" />
                            <p class="left_bottom_img_res" >We offer free shipping on all orders over $50 and all orders made before 3pm PST ship within 24 hours</p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</body>