





<?php 

$email = $_POST["email"];
if ($email != null && $email != "" && filter_var($email, FILTER_VALIDATE_EMAIL)) :

    //Mage::getModel('newsletter/subscriber')->loadByEmail($email)->unsubscribe();
    $subscriber = Mage::getModel('newsletter/subscriber')->loadByEmail($email);
    if ($subscriber->getSubscriberEmail()) {
        echo $email . " exsits<br>"; 
        $subscriber->unsubscribe();
    }

    else {
        echo $email . " does not exsits.<br>";
    }

    ?>
    <p>Sorry to see you go. <?php echo $email; ?></p>
    <?php

else: 
    //echo $email . " " . filter_var($email, FILTER_VALIDATE_EMAIL) . "LALALALLA<br>"; 
//echo Mage::getModel('newsletter/subscriber')->loadByEmail('yiyangh@compandsave.com')->getUnsubscriptionLink();
?>
<!--<p id="success_message"></p>-->
<h1>Unsubscribe from our mailing list</h1>
<div class="one_half">
    <h2>Actually, I still want to receive email.</h2>
    <p>Please update my email frequency:</p> 
    <div id="ti_update_form">
        <p id="success_message" class="altTxt"></p>
        <input type="radio" id="once" name="update_freq" value="1">
        <label for="once">
            <div class="ti-radio"></div>
            <span>Once a Month</span>
        </label><br>
        <input type="radio" id="twice" name="update_freq" value="2">
        <label for="twice">
            <div class="ti-radio"></div>
            <span>Twice a Month</span>
        </label><br>
        <p id="error_message" class="altTxt"></p>
        <label class="ti_cms_labelHide">
            <span>E-mail Address:</span>
            <input id="ti_change_fre" type="text" placeholder="Email Address"/>
        </label>
        <button type="button" class="button" id="ti_update_submit"><span><span><?php echo $this->__('Update') ?></span></span></button><br>
    </div>
</div>

<div class="one_half">
    <h2>I want to unsubscribe. </h2>
    <div class="ti_cms_eight ti_cms_centerTxt ti_cms_center ti_cms_borderAll ti_cms_bgGrey">
        <form id="ti_unsub_form" method="POST" action = "<?php echo $this->getUrl('') ?>Mail_Subscribe/unsubscribe/">
          <p>Please unsubscribe me, because:</p>
          <ul>
            <li>
                <input name="reason" value="I no longer wish to receive these emails" type="radio" id="reason1" checked/>
                <label for="reason1">
                    <div class="ti-radio"></div>
                    <span>I no longer wish to receive these emails</span>
                </label>
            </li>
            <li>
                <input name="reason" value="The emails are no longer for content that I originally signed up for" type="radio" id="reason2"/>
                <label for="reason2">
                    <div class="ti-radio"></div>
                    <span>The emails are no longer for content that I originally signed up for</span>
                </label>
            </li>
            <li>
                <input name="reason" value="I never gave my permission to receive these emails" type="radio" id="reason3"/>
                <label for="reason3">
                    <div class="ti-radio"></div>
                    <span>I never gave my permission to receive these emails</span>
                </label>
            </li>
            <li>
                <input name="reason" value="I cannot properly view those emails on my mobile device" type="radio" id="reason4" />
                <label for="reason4">
                    <div class="ti-radio"></div>
                    <span>I cannot properly view those emails on my mobile device</span>
                </label>
            </li>
            <li>
                <input name="reason" value="5" type="radio" id="reason5"/>
                <label for="reason5">
                    <div class="ti-radio"></div>
                    <span>Other: </span><input id="otherReason_input" class="otherReason" placeholder="Type reason here" type="text"/>
                </label>
            </li>
          </ul>
          <p id="unsuccess_text_unsub"></p>
          <p id="ti_unsub_errormessage"></p>
          <label class="ti_cms_labelHide">
            <span>E-mail Address:</span>
            <input id="ti_unsub_text" type="text" name="email" placeholder="Email Address">
          </label>
          <input id="ti_unsub_button" type="button" type="button" value="Remove me from the list">
        </form>
    </div>
</div>


<script type="text/javascript">
    var email = getUrlVars()['email'];
    if (validateEmail(email)) {
        jQuery("#ti_unsub_text").val(email);
        jQuery("#ti_change_fre").val(email);

    }
        
    jQuery("#ti_update_submit").click(function() {

        var emailaddress = jQuery("#ti_change_fre").val();
        console.log(emailaddress);
        if (validateEmail(emailaddress)) {
        var ti_update_freq  = jQuery('input[name=update_freq]:checked').val();

        var ti_update_url   = "<?php echo $this->getUrl(''); ?>newsletter/subscriber/new/";
        ti_update_url = ti_update_url.replace("http:", "");

        var formdata = { 
        email:emailaddress, 
        subscriber_freq: ti_update_freq
        };
        jQuery.ajax({
            url : ti_update_url,
            type: "POST",
            data : formdata,
            success: function(data, textStatus, jqXHR) {
    

            document.getElementById('error_message').innerHTML = "You've successfully updated your email frequency!";



            },
            error: function(data, textStatus, jqXHR) {
                console.log(data.error);
                console.log(textStatus);
                console.log(jqXHR);
            }


        });

        }
        else {
            jQuery("#error_message").html("sorry, your email address is not valid");
        }
    });

    jQuery("#ti_unsub_button").click(function() {
        var emailaddress = jQuery("#ti_unsub_text").val();
        console.log(emailaddress);

        if (validateEmail(emailaddress)) {
            jQuery("#ti_unsub_form").submit();
        }
        else {
            jQuery("#ti_unsub_errormessage").html("sorry, your email address is not valid");
        }


    });

</script>


<?php endif; ?>