<!-- https://www.866ink.com/magentoEE/index.php/newsletter/subscriber/new/ !-->
<style type="text/css">
#ti_subpage_message {
    display:none;
}

#ti_update_form {
    display: none;
}

</style>



<h2 id="ti_subpage_message">Thank You for subscription !!! </h2>



<form action="" method="post" id="ti_subpage_form">
    <div class="form-subscribe">
    <div class="form-subscribe-header">
        <label for="newsletter"><?php echo $this->__('Sign Up for Our Newsletter:') ?></label>
    </div>
        <div class="v-fix"><input name="email" type="text" id="newsletter" value="<?php echo $this->__('Enter your email address') ?>" onclick="this.value=='<?php echo $this->__('Enter your email address') ?>'?this.value='':''" onblur="this.value==''?this.value='<?php echo $this->__('Enter your email address') ?>':''" class="input-text required-entry validate-email" /></div>
        <span>FirstName:&nbsp;</span><input id="ti_subpage_fname" type="text"><br>
        <span>LastName:&nbsp;</span><input id="ti_subpage_lname" type="text"><br>
        <input type="radio" name="subscriber_freq" value="0" checked>Regular<br>
<input type="radio" name="subscriber_freq" value="1">Once a Month<br>
<input type="radio" name="subscriber_freq" value="2">Twice a Month<br>
     	<button type="button" class="button" id="ti_subpage_submit" title="<?php echo $this->__('Subscribe') ?>"><span><?php echo $this->__('Subscribe') ?></span></button>
        


    </div>
</form>

<!-- Update section !-->
<div id="ti_update_form">
    <p> Do you want to update your subscription information? </p>
    <span>FirstName:&nbsp;</span><input id="ti_update_fname" type="text"><br>
    <span>LastName:&nbsp;</span><input id="ti_update_lname" type="text"><br>
    <input type="radio" name="update_freq" value="0" checked>Regular<br>
    <input type="radio" name="update_freq" value="1">Once a Month<br>
    <input type="radio" name="update_freq" value="2">Twice a Month<br>
    <input type="button" value="back" onclick="window.history.go(-1);">&nbsp;<button type="button" class="button" id="ti_update_submit"><span><span><?php echo $this->__('Update') ?></span></span></button><br>

</div>




<script type="text/javascript">
//<![CDATA[
    var newsletterSubscriberFormDetail = new VarienForm('ti_subpage_form');
//]]>
</script>


<script type="text/javascript">
var ti_subpage_url   = "<?php echo $this->getUrl(''); ?>newsletter/subscriber/new/";
var ti_update_email = decodeURIComponent(getUrlVars()["email"]);
console.log(ti_update_email);
if (ti_update_email != "undefined" && ti_update_email != "") {
    jQuery('#ti_subpage_form').hide();
    jQuery.ajax({
        url : ti_subpage_url,
        type: "POST",
        data : {email: ti_update_email},
        success: function(data, textStatus, jqXHR) {
            console.log(textStatus);
            jQuery('#ti_subpage_message').show('slow');
            jQuery('#ti_update_form').show('slow');



        }

    });
}


jQuery('#ti_update_submit').click(function() {
    var ti_update_fname = jQuery('#ti_update_fname').val();
    var ti_update_lname = jQuery('#ti_update_lname').val();
    var ti_update_freq  = jQuery('input[name=update_freq]:checked').val();

    var formdata = { 
        email:ti_update_email, 
        subscriber_firstname: ti_update_fname, 
        subscriber_lastname: ti_update_lname, 
        subscriber_freq: ti_update_freq
    };

jQuery.ajax({
    url : ti_subpage_url,
    type: "POST",
    data : formdata,
    success: function(data, textStatus, jqXHR) {
        jQuery('#ti_subpage_message').html('Thank you for updating!!!');
        jQuery('#ti_subpage_form').hide();
        jQuery('#ti_update_form').hide();


    }
});
});



jQuery('#ti_subpage_submit').click(function() {
    var ti_subpage_email = jQuery('#newsletter').val();
    var ti_subpage_fname = jQuery('#ti_subpage_fname').val();
    var ti_subpage_lname = jQuery('#ti_subpage_lname').val();
    var ti_subpage_freq  = jQuery('input[name=subscriber_freq]:checked').val();

    var formdata = { 
        email:ti_subpage_email, 
        subscriber_firstname: ti_subpage_fname, 
        subscriber_lastname: ti_subpage_lname, 
        subscriber_freq: ti_subpage_freq
    };

jQuery.ajax({
    url : ti_subpage_url,
    type: "POST",
    data : formdata,
    success: function(data, textStatus, jqXHR) {
        console.log(textStatus);
        jQuery('#ti_subpage_message').show('slow');


    },
    error: function (jqXHR, textStatus, errorThrown) {
        console.log("error");
        console.log(errorThrown);
        jQuery('#ti_subpage_message').html('something is wrong');
        jQuery('#ti_subpage_message').show('slow');
    }
});




});
 


</script>