<form action="<?php echo $this->getAction() ?>" method="post" id="form-ticket" enctype="multipart/form-data">
    <div class="fieldset block">

        <h2 class="legend"><?php echo $this->__('Add New Ticket') ?></h2>

        <ul class="form-list">
            <?php if(!Mage::getSingleton('customer/session')->isLoggedIn()) :?>

            <li class="fields">
                <div class="field">
                    <label for="title" class="required ti_cms_labelHide ti-required-entry"><span><?php echo $this->__('Title') ?></span></label>
                    <div class="input-box">
                        <input type="text" name="title" title="<?php echo $this->__('Title') ?>" placeholder="<?php echo $this->__('Title') ?>" id="title" class="input-text required-entry" />
                    </div>
                </div>

                <div class="field">
                    <label for="email" class="required ti_cms_labelHide ti-required-entry"><span><?php echo Mage::helper('contacts')->__('Email') ?></span></label>
                    <div class="input-box">
                        <input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" placeholder="<?php echo $this->htmlEscape($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="email" />
                    </div>
                </div>
            </li>
            <?php else :?>
            <li class="wide">
                <label for="title" class="ti-required-entry required ti_cms_labelHide"><span><?php echo $this->__('Title') ?></span></label>
                <div class="input-box">
                    <input type="text" name="title" title="<?php echo $this->__('Title') ?>" placeholder="<?php echo $this->__('Title') ?>" id="title" class="input-text required-entry" />
                </div>
            </li>
            <?php endif; ?>

            <li class="fields">
                <div class="ti-required-entry field one_half">
                    <label for="department" class="required"><?php echo $this->__('Department') ?></label>
                    <div class="input-box ti_select_barContainer">
                        <?php echo $this->getDepartmentHtmlSelect() ?>
                    </div>
                </div>
                <?php if(Mage::getStoreConfig("helpmate/ticketForm/usePriorityOnFrontend")) :?>
                <div class="ti-required-entry field one_half">
                    <label for="priority" class="required"><?php echo $this->__('Priority') ?></label>
                    <div class="input-box ti_select_barContainer">
                        <?php echo $this->getPriorityHtmlSelect() ?>
                    </div>
                </div>
                <?php endif;?>
            </li>

            <li class="wide">
                <label class="required ti-required-entry ti_cms_labelHide" for="text"><span><?php echo $this->__('Message') ?></span></label>
                <div class="input-box">
                    <textarea id="text" placeholder="<?php echo $this->__('Message') ?>" class="input-text required-entry one" title="<?php echo $this->__('Message') ?>" name="text" rows="3"></textarea>
                </div>
            </li>
            
            <?php echo $this->getChildHtml('form.additional.info'); ?>
        </ul>
    </div>
    <div class="buttons-set">
        <div>
            <p class="required altTxt"><?php echo $this->__('* Required Fields') ?></p>
        </div>
        <a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link ti_button"><?php echo $this->__('Back') ?></a> &nbsp;
        <button type="submit" title="<?php echo $this->__('Save Ticket') ?>" class="button"><span><span><?php echo $this->__('Save Ticket') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-ticket', true);
//]]>
</script>
