<!-- Page canonical name: /expired -->

<!-- CSS -->
<link href="<?php echo $this->getSkinUrl('css')?>/articles/ti-article.css" type="text/css" rel="stylesheet" />
<link href="<?php echo $this->getSkinUrl('css')?>/campaigns/2015/01-gen.css" type="text/css" rel="stylesheet" />

<!-- JS - Only include what you need-->
<script type="text/javascript">document.cookie ="couponcode=EXP12; expires=Wed, 1 January 3000 23:59:59 UTC; path=/";</script>
<div class="ti-cms-articleContent_area ti-gen-contain">
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-4 ti_hide_767">
				<img src="<?php echo $this->getSkinUrl('images/campaigns/2015/01-gen/expired.jpg');?>" alt="Save 12% right now!"/>
			</div>
			<div class="col-xs-12 col-sm-8">
				<h1><span class="ti-gen-intro altTxt">Sorry!</span> The coupon you were looking for has expired!</h1>
				<h3 class="ltWeight">Please <a class="altTxt" href="<?php echo $this->getUrl('contact');?>" target="_blank">contact us</a> or redeem your 12% off courtesy coupon below:</h3>
				<p class="text_center"><span class="ti-gen-coupon"><span class="icon-point-right"></span> EXP12</span></p>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-8 col-sm-offset-4">
					<div class="ti_input_bar">
					<?php $catalogSearchHelper = $this->helper('catalogsearch'); ?>
						<form id="search_mini_form-2" action="<?php echo $catalogSearchHelper->getResultUrl();?>" method="get">
							<input type="search" name="<?php echo $catalogSearchHelper->getQueryParamName(); ?>" id="search1" placeholder="Type your printer or ink model..." />
							<input type="submit" name="Submit" id="search_submit1" value="Search" title="<?php echo $this->__('Search'); ?>"/>
						</form>
					</div>
				</div>
			</div>
		</div>
		<div class="row ti-gen-disclaimer">
			<div class="col-xs-10 col-xs-offset-1">
				<p><strong>Disclaimer:</strong> You can use this coupon code until time ceases to exist. Coupon codes cannot be combined with any other offers or promotions and cannot be applied to past purchases. Offers valid online at TomatoInk.com only. TomatoInk.com reserves the right to remove, add or change items on this promotion without prior notice.</p>
			</div>
		</div>
	</div>
</div>