<!-- Page canonical name: /expired -->

<!-- CSS -->
<link href="<?php echo $this->getSkinUrl('css')?>/articles/ti-article.css" type="text/css" rel="stylesheet" />
<link href="<?php echo $this->getSkinUrl('css')?>/campaigns/2015/01-gen.css" type="text/css" rel="stylesheet" />

<!-- JS - Only include what you need-->
<script src="<?php echo $this->getSkinUrl("js")?>/ti-global/ti-searchform.js" type="text/javascript"></script>


<script type="text/javascript">document.cookie ="couponcode=EXP12; expires=Wed, 1 January 3000 23:59:59 UTC; path=/";</script>

<div class="container-fluid ti-cms-articleContent_area ti-gen-contain">
	<div class="row">
		<div class="col-sm-4 ti_hide_479">
			<img src="<?php echo $this->getSkinUrl('images/ti-home/save-big.jpg');?>" alt="Save 12% right now!"/>
		</div>
		<div class="col-xs-12 col-sm-8">
			<h1>Sorry! The coupon you were looking for has expired!</h1>
			<h2>Please <a class="altTxt" href="<?php echo $this->getUrl('contact');?>" target="_blank">contact us</a> or redeem your 12% off courtesy coupon below:</h2>
			<p class="ti-gen-coupon">EXP12</p>
			<div class="ti_input_bar">
				<form id="nxt-ac-form" onsubmit="return submitSearch5();" action="http://search.tomatoink.com/search" method="get" name="form5">
					<input type="text" name="keywords" autocomplete="off" placeholder="Type your printer or ink model..." id="search_v5_5" onkeypress="return handleEnter5(this,event)">
					<input type="submit" border="0" onclick="submitSearch5();" value="Search" name="imageField">
				</form>
			</div>
		</div>
	</div>
	<div class="row ti-gen-disclaimer">
		<div class="col-xs-1"></div>
		<div class="col-xs-10">
			<p><strong>Disclaimer:</strong> You can use this coupon code until time ceases to exist. Coupon codes cannot be combined with any other offers or promotions and cannot be applied to past purchases. Offers valid online at TomatoInk.com only. TomatoInk.com reserves the right to remove, add or change items on this promotion without prior notice.</p>
		</div>
		<div class="col-xs-1"></div>
	</div>
</div>

<!-- JS - Only include what you need-->