<?php
    $_layout = $this->getLayout();
    $_dob    = $_layout->createBlock('customer/widget_dob');
    $_gender = $_layout->createBlock('customer/widget_gender');
    $_taxvat = $_layout->createBlock('customer/widget_taxvat');
    $_isCustomerLoggedIn = $this->isCustomerLoggedIn();
    $_address = $this->getAddress();
    $_prefix  = 'billing';

    $status = Mage::getStoreConfig('firecheckout/address_form_status');
    if ('hidden' !== $status['postcode']) {
        $status['postcode'] = 'required'; // used to render asterisk
    }
    if (Mage::getStoreConfig('general/region/state_required')) {
        $status['region'] = 'required'; // used to render asterisk
    }
    $fields = array(
        'name' => array(),
        'email' => array(
            'class'  => 'input validate-email ti_checkout_info',
            'label'  => 'Email Address',
            'status' => $_isCustomerLoggedIn ? 'hidden' : 'required',
            'placeholder' => 'Email'
        ),
        'company' => array(
            'class' => 'ti_checkout_info',
            'label' => 'Company',
            'placeholder' => 'Company'
        ),
        'city' => array(
            'class' => 'ti_checkout_info',
            'label' => 'City',
            'placeholder' => 'City'
        ),
        'postcode' => array(
            'class' => 'validate-zip-international ti_checkout_info',
            'label' => 'Zip/Postal Code',
            'placeholder' => 'Postal Code'
        ),
        'fax' => array(
            'class' => 'ti_checkout_info',
            'label' => 'Fax',
            'placeholder' => 'Fax'
        ),
        'telephone' => array(
            'class' => 'ti_checkout_info',
            'label' => 'Telephone',
            'placeholder' => 'Telephone'
        ),
        'street1' => array(
            'class' => 'ti_checkout_info',
            'label' => 'Address',
            'title' => 'Street Address',
            'name'  => $_prefix . '[street][]',
            'placeholder' => $_address->getStreet(1) ? $_address->getStreet(1) : 'Address'
        ),
        'country_id' => array(
            'label' => 'Country',
            'required_to_render' => 1
        ),
        'region' => array(
            'label' => 'State/Province',
            'required_to_render' => 1
        ),
        'dob' => array(
            'status' => (!$_isCustomerLoggedIn && $_dob->isEnabled()) ? 'optional' : 'hidden'
        ),
        'gender' => array(
            'status' => (!$_isCustomerLoggedIn && $_gender->isEnabled()) ? 'optional' : 'hidden'
        ),
        'taxvat' => array(
            'status' => (!$_isCustomerLoggedIn && $_taxvat->isEnabled()) ? 'optional' : 'hidden'
        )
    );

    $addressHelper = $this->helper('customer/address');
    if (method_exists($addressHelper, 'isVatAttributeVisible')) {
        $fields['vat_id'] = array(
            'status' => $addressHelper->isVatAttributeVisible() ? 'optional' : 'hidden',
            'class'  => 'input ' . $addressHelper->getAttributeValidationClass('vat_id'),
            'label'  => 'VAT Number'
        );
    }
?>

<div id="billing-address" class="btcf">
    <?php if (!$this->canShip() || !Mage::getStoreConfig('firecheckout/general/shipping_address')): ?>
        <div class="ti_cms_block_headerBar-green"><span><?php echo $this->helper('checkout')->__('Address'); ?></span></div>
    <?php else: ?>
        <div class="ti_cms_block_headerBar-green"><h2 class="white ti_headerH1" id="ti_checkoutStep1"><span class="ti_checkoutStep">1</span><?php echo $this->helper('checkout')->__(' Billing Information'); ?></h2></div>
    <?php endif; ?>
    <div class="block-content">
        <ul class="ti_checkout_inputField">
        <?php if ($this->customerHasAddresses()): ?>
            <li class="one">
                <label for="billing-address-select"><span><?php echo $this->helper('checkout')->__('Select a billing address from your address book or enter a new address.') ?></span></label>
                <div class="ti_select_barContainer">
                    <?php echo $this->getAddressesHtmlSelect('billing') ?>
                </div>
            </li>
        <?php endif; ?>
        <li id="billing-new-address-form"<?php if ($this->hasCustomerAddressId()): ?> style="display:none;"<?php endif; ?>>
            <fieldset style="width: 98%;display: block; float: left; margin: 0 1%">
                <input type="hidden" name="billing[address_id]" value="<?php echo $_address->getId() ?>" id="billing:address_id" />
                <!--<ul>-->
                    <?php foreach (Mage::helper('firecheckout/address')->getSortedFields() as $row) : ?>
                        <?php
                        $countVisible          = 0;
                        $countRequiredToRender = 0;

                        foreach ($row as $key => $field) { // do not use break in this cycle to fill statuses for all fields
                            if (!isset($fields[$field])) { // shipping address doesn't have all of the fields
                                unset($row[$key]);
                                continue;
                            }

                            if (empty($status[$field])) {
                                if (!empty($fields[$field]['status'])) {
                                    $status[$field] = $fields[$field]['status'];
                                } else {
                                    $status[$field] = 'required';
                                }
                            }
                            if (!empty($fields[$field]['required_to_render'])) {
                                $countRequiredToRender++;
                            }
                            if ('hidden' !== $status[$field]) {
                                $countVisible++;
                            }
                        }

                        ?>

                        <?php if (!$countVisible && !$countRequiredToRender): continue; endif; ?>
                        <?php foreach ($row as $field) : ?>

                            <?php //$isMulticolumn = ( $field == 'street1' ||  $field == 'name' );?>
                        <li class="<?php if($field == 'street1') echo 'one_checkout';elseif($field == 'name') echo 'one_name'; else echo 'one_half' ;?>" <?php echo ('hidden' !== $status[$field]) ? '' : 'style = "display: none;"' ?>>

                                <?php $required = ('required' === $status[$field]); ?>

                                    <?php if ('name' === $field) : ?>
                                        <?php echo $this->getLayout()->createBlock('compandsave_productselector/name')->setObject($_address)->setFieldIdFormat($_prefix . ':%s')->setFieldNameFormat($_prefix . '[%s]')->toHtml() ?>
                                    <?php else : ?>

                                    <?php if ('hidden' === $status[$field]) :
                                            if (empty($fields[$field]['required_to_render'])) :
                                                continue;
                                            endif; ?>

                                        <div style="display: none;">
                                    <?php endif; ?>



                                    <?php if ('dob' === $field): ?>
                                        <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat($_prefix . ':%s')->setFieldNameFormat($_prefix . '[%s]')->toHtml() ?>
                                    <?php elseif ('gender' === $field): ?>
                                        <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat($_prefix . ':%s')->setFieldNameFormat($_prefix . '[%s]')->toHtml() ?>
                                    <?php elseif ('taxvat' === $field): ?>
                                        <?php echo $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())->setFieldIdFormat($_prefix . ':%s')->setFieldNameFormat($_prefix . '[%s]')->toHtml() ?>
                                    <?php else: ?>
                                        <label for="<?php echo $_prefix ?>:<?php echo $field ?>"
                                            class="ti_cms_labelHide"
                                            ><span><?php echo $this->__($fields[$field]['label']) ?></span></label>
                                        <div class="<?php echo $required ? 'ti-required-entry' : '' ?> ti_checkout_info">
                                            <?php if ('country_id' === $field) : ?>
                                            <div class="ti_select_barContainer">
                                                <?php echo $this->getCountryHtmlSelect($_prefix) ?>
                                            </div>
                                            <?php elseif ('region' === $field): ?>
                                                <div id="ti_hide_billing_state" class="ti_select_barContainer">
                                                <select id="<?php echo $_prefix ?>:region_id" name="<?php echo $_prefix ?>[region_id]"
                                                    title="<?php echo (empty($fields[$field]['title']) ? $this->__($fields[$field]['label']) : $this->__($fields[$field]['title'])) ?>"
                                                    class="validate-select<?php echo $required ? ' required-entry' : '' ?>" class="ti_select_barContainer"> 
                                                    <option value=""><?php echo $this->__('Select State/ Province') ?></option>
                                                </select>
                                                </div>
                                                <script type="text/javascript">
                                                //<![CDATA[
                                                    $('<?php echo $_prefix ?>:region_id').setAttribute('defaultValue',  "<?php echo $_address->getRegionId() ?>");
                                                //]]>
                                                </script>
                                                <input type="text" id="<?php echo $_prefix ?>:region" name="<?php echo $_prefix ?>[region]"
                                                    placeholder="<?php if($this->escapeHtml($_address->getRegion())) echo $this->escapeHtml($_address->getRegion()); else echo 'State/Province'; ?>"
                                                    title="<?php echo (empty($fields[$field]['title']) ? $this->__($fields[$field]['label']) : $this->__($fields[$field]['title'])) ?>"
                                                    class="<?php echo $required ? ' required-entry' : '' ?> ti_checkout_info" style="display:none;"
                                                />
                                                
                                            <?php else: ?>
                                                <?php
                                                    if (isset($fields[$field]['placeholder'])):
                                                        $value = $fields[$field]['placeholder'];
                                                    else:
                                                        $method = 'get' . ucfirst($field);
                                                        $value = $_address->{$method}();
                                                    endif;
                                                ?>
                                                <input type="text"
                                                    name="<?php echo (empty($fields[$field]['name']) ? $_prefix . '[' . $field . ']' : $fields[$field]['name']) ?>"
                                                    id="<?php echo $_prefix ?>:<?php echo $field ?>"
                                                    placeholder = "<?php echo $this->escapeHtml($value) ?>"
                                                    title="<?php echo (empty($fields[$field]['title']) ? $this->__($fields[$field]['label']) : $this->__($fields[$field]['title'])) ?>"
                                                    class="<?php echo $fields[$field]['class'] ?><?php echo $required ? ' required-entry' : '' ?>"
                                                />
                                            <?php endif ?>
                                        </div>
                                    <?php endif; ?>



                                    <?php if ('hidden' === $status[$field]) : ?>
                                        </div>
                                    <?php endif; ?>

                                <?php endif; ?>

                                <?php if ('street1' === $field) : ?>
                                    <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                                        </li>
                                        <li class="one_checkout">
                                            <div class="input-box ti_checkout_info">
                                                <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="<?php echo $_prefix ?>[street][]" id="<?php echo $_prefix ?>:street<?php echo $_i?>" value="<?php echo $this->escapeHtml($_address->getStreet($_i)) ?>" class="ti_checkout_info" />
                                            </div>
                                    <?php endfor ?>
                                <?php endif; ?>

                            <?php endforeach; ?>
                        </li>
                    <?php endforeach; ?>

                    <?php $addressAttributes = $this->getChild('customer_form_' . $_prefix . '_address_user_defined_attributes');?>
                    <?php if ($addressAttributes): ?>
                        <?php $addressAttributes->setEntity($_address)->setEntityType('customer_address');?>
                        <?php $addressAttributes->setFieldIdFormat($_prefix . ':%1$s')->setFieldNameFormat($_prefix . '[%1$s]');?>
                        <?php echo $addressAttributes->setExcludeFileAttributes(true)->setShowContainer(false)->toHtml()?>
                    <?php endif;?>

                    <?php $customerAttributes = $this->getChild('customer_form_customer_user_defined_attributes');?>
                    <?php if ($customerAttributes): ?>
                        <?php $customerAttributes->setEntityModelClass('customer/customer')->setFieldIdFormat($_prefix . ':%1$s');?>
                        <?php $customerAttributes->setFieldNameFormat($_prefix . '[%1$s]')->setShowContainer(false);?>
                        <?php echo $customerAttributes->setExcludeFileAttributes(true)->toHtml()?>
                    <?php endif;?>

                    <?php if (!$this->isCustomerLoggedIn()) : ?>
                        <?php
                            $registrationMode = Mage::getStoreConfig('firecheckout/general/registration_mode');
                            $register = $this->getRegisterAccount();
                            $isAllowedGuest = Mage::helper('firecheckout')->isAllowedGuestCheckout();
                        if ($isAllowedGuest || $register) : ?>
                            <li class="control one_half">
                                <input type="checkbox" name="billing[register_account]" value="1" title="<?php echo $this->__('Create account for later use') ?>" id="billing:register_account" onclick="if(window.billing) billing.setCreateAccount(this.checked);"<?php if ($register || 'optional-checked' == $registrationMode) : ?> checked="checked"<?php endif;?> class="altTxt" />
                                <label for="billing:register_account" class="altTxt btcf"><div class="ti-checkbox"></div> <span><?php echo $this->__('Save your information for future orders') ?></span></label>
                                
                            </li>
                        <?php else: ?>
                            <li class="no-display">
                                <input type="hidden" name="billing[register_account]" value="1"/>
                            </li>
                        <?php endif ?>
                        <?php if (Mage::helper('firecheckout')->canShowNewsletter()) : ?>
                            <li class="control one_half">
                                <input type="checkbox" id="newsletter-signup" name="newsletter" value="1"<?php if (Mage::getStoreConfig('firecheckout/general/newsletter_checkbox_state')) : ?> checked="checked"<?php endif; ?> title="<?php echo Mage::helper('newsletter')->__('Sign up for our newsletter') ?>" class="altTxt" />
                                <label for="newsletter-signup" class="altTxt btcf"><div class="ti-checkbox"></div> <span><?php echo Mage::helper('newsletter')->__("Sign up for TomatoInk's bi-weekly email deals") ?></span></label>
                                
                            </li>
                        <?php endif; ?>
                        <?php if ('hidden' !== $registrationMode || $register) : ?>
                            <li class="one_half" id="register-customer-password" <?php if ('optional' == $registrationMode && !$register) : ?>style="display: none;" <?php endif; ?>>
                                <div class="one_half ti-required-entry">
                                    <label for="billing:customer_password" class="required altTxt"><span><?php echo $this->__('Password') ?></span></label>
                                    <div class="input-box">
                                        <input type="password" name="billing[customer_password]" id="billing:customer_password" title="<?php echo $this->__('Password') ?>" class="input required-entry validate-password" />
                                    </div>
                                </div>
                                <div class="one_half ti-required-entry">
                                    <label for="billing:confirm_password" class="required altTxt"><span><?php echo $this->__('Confirm Password') ?></span></label>
                                    <div class="input-box">
                                        <input type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="input required-entry validate-cpassword" />
                                    </div>
                                </div>
                            </li>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                        <li class="control one_half">
                            <input type="checkbox" name="billing[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book" <?php if ($_address->getSaveInAddressBook()):?> checked="checked"<?php endif;?> />
                            <label class="altTxt btcf" for="billing:save_in_address_book"><div class="ti-checkbox"></div><span><?php echo $this->__('Save in address book') ?></span></label>
                        </li>
                    <?php else:?>
                        <li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></li>
                    <?php endif; ?>
                    <?php echo $this->getChildHtml('form.additional.info'); ?>
                <!--</ul>-->
            </fieldset>
        </li>
        <?php /* Extensions placeholder */ ?>
        <?php echo $this->getChildHtml('checkout.onepage.billing.extra')?>

        <?php $additional = $this->getChildHtml('billing.additional.container');
        if (!empty($additional)) : ?>
            <li class="billing-additional">
                <?php echo $additional; ?>
            </li>
        <?php endif; ?>
        </ul>
    <?php if (!$this->canShip() || !Mage::getStoreConfig('firecheckout/general/shipping_address')): ?>
        <input type="hidden" name="billing[use_for_shipping]" value="1" />
    <?php else: ?>
        <input type="hidden" name="billing[use_for_shipping]" id="billing:use_for_shipping" value="<?php if ($this->isUseBillingAddressForShipping()):?>1<?php else:?>0<?php endif; ?>" />
    <?php endif; ?>
    <script type="text/javascript">
    //<![CDATA[
        var billing = new Billing();
        var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'billing:postcode');
    //]]>
    </script>
    </div>
</div>
