<?php if ($this->isPossibleFireCheckout()):?>
    <button title="<?php echo $this->__('Proceed to Checkout') ?>" class="button btn-proceed-checkout btn-checkout checkout-types one_third<?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?> onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';"><span class="icon-lock"><?php echo $this->__('Proceed to checkout') ?></span></button>
<?php endif?>
