<div id="giftcard-account" class="one btcf">
    <div class="ti_cms_block_headerBar-green"><h2 class="white ti_headerH1"><?php echo $this->__(' Gift Cards') ?></h2></div>
    <div class="giftcard-form ti_cms_gradient_block">
        <?php
            echo $this->getMessagesBlock()->getGroupedHtml();
            $this->getMessagesBlock()->getMessageCollection()->clear();
        ?>
        <div class="giftcard">
            <label class="altTxt btcf" for="giftcard_code"><span><?php echo $this->__('Enter the gift card code') ?></span></label>
            <div class="input-box">
                <div class="input-field-wrapper">
                    <input class="input-text" id="giftcard_code" name="giftcard_code" value="" />
                </div>
                &nbsp; <button class="button" id="giftcard-add" type="button" value="<?php echo $this->__('Add Gift Card') ?>"><span><span><?php echo $this->__('Add Gift Card') ?></span></span></button>
            </div>
            <script type="text/javascript">
            //<![CDATA[
            $('giftcard-add') && $('giftcard-add').observe('click', function(e) {
                var code = $('giftcard_code');
                if (!code.value.length) {
                    code.addClassName('required-entry');
                    Validation.validate(code);
                    code.removeClassName('required-entry');
                    return;
                }
                checkout.update(checkout.urls.giftcard, {
                    'review': 1
                });
            });
            //]]>
            </script>
        </div>
    </div>
</div>
