<?php
$field = Mage::getStoreConfig("helpmate/ticketForm/field0");
if (!empty($field)) :?>
<li class="wide">
    <label for="title" ><?php echo $this->__($field) ?></label>

    <div class="input-box">
        <input type="text" name="field0" title="<?php echo $this->__($field) ?>" id="field0" class="input-text" />
    </div>
</li>
<?php endif;?>

<?php
$field = Mage::getStoreConfig("helpmate/ticketForm/field1");
if (!empty($field)) :?>
<li class="wide">
    <label for="title" ><?php echo $this->__($field) ?></label>

    <div class="input-box">
        <input type="text" name="field1" title="<?php echo $this->__($field) ?>" id="field1" class="input-text" />
    </div>
</li>
<?php endif;?>

<?php
$field = Mage::getStoreConfig("helpmate/ticketForm/field2");
if (!empty($field)) :?>
<li class="wide">
    <label for="title" ><?php echo $this->__($field) ?></label>

    <div class="input-box">
        <input type="text" name="field2" title="<?php echo $this->__($field) ?>" id="field2" class="input-text" />
    </div>
</li>
<?php endif;?>

