 <script type="text/javascript">
function addproduct_query(product_id) {

    var addtocart_url = "<?php //echo $checkout_url;?>" + "checkout/cart/add/product/" + product_id + "/qty/";
    var qty_id = "product_qty_" + product_id;
    var product_qty = document.getElementById(qty_id).value;
    if (product_qty==0) product_qty=1;
    addtocart_url += product_qty + "/form_key/" + "<?php //echo $formKey;?>";// + "/<?php //echo $bundle_option; ?>"
    
    var bundle_product = document.getElementById('bundle_' + product_id)
    if (bundle_product.value != "") addtocart_url += bundle_product.value + product_qty;
    //alert(addtocart_url);
    window.location = addtocart_url;
}

</script> 