<?php $collection = $this->getCollection();
if($collection && count($collection) ): ?>
    <ul>
        <?php foreach ($collection as $_category):?>
        <li>
            <h4><?php echo $_category->getName() ?></h4>
            <ul class="knowledge-articles-list">
                <?php foreach ($_category->getFaqs() as $_faq):?>
                <li>
                    <a href="<?php echo $this->getUrl(
                        'knowledgebase/index/view', array('faq' => $_faq->getIdentifier()))
                    ?>"><?php echo $_faq->getTitle() ?></a>&nbsp;
                </li>
                <?php endforeach; ?>
            </ul>
        </li>
        <?php endforeach; ?>
    </ul>

<?php else: ?>
    <p><?php echo $this->__('You have no categories.') ?></p>
<?php endif; ?>
