<?php $current_url = $this->getUrl(''); ?>
<div id="ti_footer_row" class="btcf">
	<div class="ti_cms_contain">


		<div id="ti_footer_home_hide" class="clear">
			<div class="ti_footer_top_block two_third">
				<div id="ti_footer_email_cta" class="one_fourth">
					<p>Receive monthly deals:</p>
				</div>
				<div class="three_fourth">
					<div id="ti_footer_emailSubmit" class="ti_input_bar">
						<form action="<?php echo $current_url; ?>Mail_Subscribe/" method="get" id="newsletter-validate-detail">
					        <input name="email" type="text" id="newsletter" placeholder="Email address" class="input-text required-entry validate-email" />
					     	<button type="submit" value="<?php echo $this->__('Sign Up') ?>" class="button" title="<?php echo $this->__('Subscribe') ?>"><?php echo $this->__('Sign Up') ?></button> 
				        </form>
					</div>
				</div>
			</div>
			<div class="ti_footer_top_block one_third">
				<p class="ti_social_media">
					<a href="http://www.facebook.com/tomatoinktoner" target="_blank" class="ti_social_media_btn fb"><span>Facebook</span></a>
					<a href="http://twitter.com/tomatoinktoner" target="_blank" class="ti_social_media_btn tw"><span>Twitter</span></a>
					<a href="https://plus.google.com/u/0/112582653541709057320" target="_blank" class="ti_social_media_btn gg"><span>Google+</span></a>
					<a href="http://blog.tomatoink.com/" target="_blank" class="ti_social_media_btn bl"><span>Blogger</span></a>
					<a href="http://pinterest.com/tomatoinktoner/" target="_blank" class="ti_social_media_btn pn"><span>Pinterest</span></a>
				</p>
			</div>
		</div>
		<script type="text/javascript">
        	//var ti_current_url = window.location.href;
        	//if (ti_current_url == "<?php echo $current_url ?>") document.getElementById('ti_footer_home_hide').style.display="none";
        </script>
		<div class="ti_footer_links_block one_third clear">
			<h2>Company</h2>
			<ul class="ti_menu vertical_menu">
				<li><a href="<?php echo $current_url ?>about"><span>About Us</span></a></li>
				<li><a href="<?php echo $current_url ?>contact"><span>Contact Us</span></a></li>
				<li><a href="<?php echo $current_url ?>privacy-policy"><span>Privacy Policy</span></a></li>
				<li><a href="<?php echo $current_url ?>terms"><span>Terms &amp; Conditions</span></a></li>
				<li><a href="<?php echo $current_url ?>wholesale"><span>Corporate Account</span></a></li>
				<li><a href="<?php echo $current_url ?>become-reseller"><span>Reseller Program</span></a></li>
				<li><a href="http://www.shareasale.com/shareasale.cfm?merchantID=40756" target="_blank"><span>Become an Affiliate</span></a></li>
			</ul>
		</div>
		<div class="ti_footer_links_block one_third middle">
			<h2>Resources</h2>
			<ul class="ti_menu vertical_menu">
				<li><a href="<?php echo $current_url ?>shipping-policy"><span>Shipping Policy</span></a></li>
				<li><a href="<?php echo $current_url ?>return-policy"><span>Return Policy</span></a></li>
				<li><a href="<?php echo $current_url ?>low-price-guarantee"><span>Low Price Guarantee</span></a></li>
				<li><a href="<?php echo $current_url ?>ink-toner-troubleshooting"><span>Ink Troubleshooting</span></a></li>
				<li><a href="<?php echo $current_url ?>compatible-remanufactured-cartridges-information"><span>Ink Knowledge Base</span></a></li>
				<li><a href="<?php echo $current_url ?>printer-drivers-support"><span>Printer Support</span></a></li>
				<li><a href="<?php echo $current_url ?>environmentally-friendly-green-ink-and-toner-cartridges"><span>Environment Friendly Inks</span></a></li>
			</ul>
		</div>
		
		<div class="ti_footer_links_block one_third">
			<h2>Account</h2>
			<ul class="ti_menu vertical_menu">
				<li><a href="<?php echo $current_url ?>customer/account/index/"><span>My Account</span></a></li>
				<li><a href="<?php echo $current_url ?>checkout/cart/"><span>View Cart</span></a></li>
				<li><a href="<?php echo $current_url ?>order-tracking"><span>Order Status</span></a></li>
				<li><a href="<?php echo $current_url ?>faq"><span>Help</span></a></li>
			</ul>
		</div>
	</div>
</div>
<div id="ti_footer_copyright_row" class="btcf">
	<div class="ti_cms_contain">
		<div class="ti_footer_block">
			<p class="clear">Copyright <?php echo $this->getCopyright() ?></p>
		</div>
		<div class="ti_footer_block">
			<a href="https://www.mcafeesecure.com/RatingVerify?ref=www.tomatoink.com" target="_blank" class="ti-footer-security">
				<img width="94" height="54" border="0" oncontextmenu="alert('Copying Prohibited by Law - McAfee SECURE is a Trademark of McAfee, Inc.'); return false;" alt="McAfee SECURE sites help keep you safe from identity theft, credit card fraud, spyware, spam, viruses and online scams" src="//images.mcafeesecure.com/meter/www.tomatoink.com/23.gif"></img>
			</a>
		</div>
	</div>
</div>



<script type="text/javascript">
//<![CDATA[
    var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
//]]>
</script>
<?php echo $this->getChildHtml('jsfooter') ?>