<div id="ti_footer_row" class="btcf">
	<div class="ti_cms_contain">


		<div id="ti_footer_home_hide" class="clear">
			<div class="ti_footer_top_block two_third">
				<div id="ti_footer_email_cta" class="one_fourth">
					<p>Receive monthly deals:</p>
				</div>
				<div class="three_fourth">
					<div id="ti_footer_emailSubmit" class="ti_input_bar">
<form action="<?php echo $this->getUrl(''); ?>Mail_Subscribe/" method="get" id="newsletter-validate-detail">
    <div class="form-subscribe">
    <div class="form-subscribe-header">
        <label for="newsletter"><?php echo $this->__('Sign Up for Our Newsletter:') ?></label>
    </div>
        <div class="v-fix"><input name="email" type="text" id="newsletter" value="<?php echo $this->__('Enter your email address') ?>" onclick="this.value=='<?php echo $this->__('Enter your email address') ?>'?this.value='':''" onblur="this.value==''?this.value='<?php echo $this->__('Enter your email address') ?>':''" class="input-text required-entry validate-email" /></div>
     	<button type="submit" class="button" title="<?php echo $this->__('Subscribe') ?>"><span><span><?php echo $this->__('Subscribe') ?></span></span></button> 

    </div>
</form>



					</div>
				</div>
			</div>
			<div class="ti_footer_top_block one_third">
				<p class="ti_social_media">
					<a href="http://www.facebook.com/tomatoinktoner" target="_blank" class="ti_social_media_btn fb"></a>
					<a href="http://twitter.com/tomatoinktoner" target="_blank" class="ti_social_media_btn tw"></a>
					<a href="https://plus.google.com/u/0/112582653541709057320" target="_blank" class="ti_social_media_btn gg"></a>
					<a href="http://blog.tomatoink.com/" target="_blank" class="ti_social_media_btn bl"></a>
					<a href="http://pinterest.com/tomatoinktoner/" target="_blank" class="ti_social_media_btn pn"></a>
				</p>
			</div>
		</div>
		<!-- check if it is home and hide footer subscribe section !-->
		<script type="text/javascript">
        	var ti_current_url = window.location.href;
        	if (ti_current_url == "<?php echo $this->getUrl('') ?>") document.getElementById('ti_footer_home_hide').style.display="none";
        </script>
<!-- valify the subscript form !-->
        <script type="text/javascript">
//<![CDATA[
    var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
//]]>
</script>


		<div class="ti_footer_links_block one_third clear">
			<h2>Company</h2>
			<ul class="ti_menu">
				<li><a href=""><span>About</span></a></li>
				<li><a href=""><span>About</span></a></li>
				<li><a href=""><span>About</span></a></li>
				<li><a href=""><span>About</span></a></li>
				<li><a href=""><span>About</span></a></li>
				<li><a href=""><span>About</span></a></li>
				<li><a href=""><span>About</span></a></li>
				<li><a href=""><span>About</span></a></li>
				<li><a href=""><span>About</span></a></li>
				<li><a href=""><span>About</span></a></li>
			</ul>
		</div>
		<div class="ti_footer_links_block one_third middle">
			<h2>Resources</h2>
			<ul class="ti_menu">
				<li><a href=""><span>About</span></a></li>
				<li><a href=""><span>About</span></a></li>
				<li><a href=""><span>About</span></a></li>
				<li><a href=""><span>About</span></a></li>
				<li><a href=""><span>About</span></a></li>
				<li><a href=""><span>About</span></a></li>
				<li><a href=""><span>About</span></a></li>
				<li><a href=""><span>About</span></a></li>
				<li><a href=""><span>About</span></a></li>
				<li><a href=""><span>About</span></a></li>
			</ul>
		</div>
		<div class="ti_footer_links_block one_third">
			<h2>Account</h2>
			<ul class="ti_menu">
				<li><a href=""><span>About</span></a></li>
				<li><a href=""><span>About</span></a></li>
				<li><a href=""><span>About</span></a></li>
				<li><a href=""><span>About</span></a></li>
				<li><a href=""><span>About</span></a></li>
				<li><a href=""><span>About</span></a></li>
			</ul>
		</div>
	</div>
</div>
<div id="ti_footer_copyright_row" class="btcf">
	<div class="ti_cms_contain">
		<div class="ti_footer_block">
			<p class="clear">Copyright &copy; 2014 TomatoInk &bull; 39120 Argonaut Way &bull; Fremont Hub #532 &bull; Fremont, CA 94538 &bull; All Rights Reserved</p>
		</div>
		<div class="ti_footer_block">
			<a href="https://www.mcafeesecure.com/RatingVerify?ref=www.tomatoink.com" target="_blank" class="ti-footer-security">
				<img width="94" height="54" border="0" oncontextmenu="alert('Copying Prohibited by Law - McAfee SECURE is a Trademark of McAfee, Inc.'); return false;" alt="McAfee SECURE sites help keep you safe from identity theft, credit card fraud, spyware, spam, viruses and online scams" src="//images.mcafeesecure.com/meter/www.tomatoink.com/23.gif"></img>
			</a>
		</div>
	</div>
</div>