
	
	<!--Fonts for all pages-->
	<link href='http://fonts.googleapis.com/css?family=Oleo+Script' rel='stylesheet' type='text/css'>
	<script type="text/javascript" src="//use.typekit.net/mbd0rqf.js"></script>
	<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
	<!--end fonts-->
	
	<!--[if gte IE 9]>
  		<style type="text/css">
    		.gradient, .ti_cms_gradient_block {
       		filter: none;
   			 }
  		</style>
	<![endif]-->


	<script type="text/javascript">
		var homepage = "<?php if ($this->getIsHomePage()) echo 'true'; else echo 'false'?>";
		var ti_global_url = "<?php echo $this->getUrl('');?>";
		ti_global_url = ti_global_url.match(/.*(?=index.php\/)/);
		
	</script>


	<div id="ti_header_row">
		<?php $getCouponModel = Mage::getResourceModel('compandsave_variable/coupon_collection')
				->addFieldToFilter('entity_type_id','Coupon')
				->addFieldToFilter('status','1')
				->addFieldToFilter('visibility','1')
				->getFirstItem()
				->load();
		?>
		<div class="ti_cms_contain ti_hide_479" id="ti_main_coupon">
			<p id="ti_header_click_coupon"><span>Fresh Deals</span><br>Get this month's coupon.</p>
			<p id="ti_header_coupon_desc">
				<span id="ti_header_coupon_info"><?php echo $getCouponModel['description'];?></span><br>
				<span id="ti_header_coupon_code"><?php echo $getCouponModel['value']; ?></span><br>
				<span id="ti_header_coupon_exp" class="ti_small_text"><?php echo $getCouponModel['expiry_date']; ?></span>
			</p>
			<div id="ti_main_coupon_arrow"></div>
		</div>
		<div id="ti_header_quick_links" class="btcf">
			<div class="ti_cms_contain">
				<div class="ti_header_top_block">
					<p><strong>Free shipping on orders of $50 or more!</strong> Reg: $3.99</p>
				</div>
				<div class="ti_header_top_block">
					
						<?php echo $this->getChildHtml('topLinks') ?>
					
				</div>
				<div class="ti_header_nav_block clear">
					<div id="ti_header_nav_mini">
						<select>
							<option selected="selected" disabled="disabled">Shop by...</option>
							<option>HP</option>
							<option>Brother</option>
							<option>Epson</option>
							<option>Canon</option>
							<option>Lexmark</option>
							<option>Samsung</option>
							<option>Dell</option>
							<option>Kodak</option>
							<option>Konica-Minolta</option>
							<option>Okidata</option>
							<option>Xerox</option>
							<option>Kyocera-Mita</option>
							<option>Pitney Bowes</option>
							<option>Sharp</option>
							<option>IBM</option>
							<option>Ricoh</option>
							<option>Apple</option>
							<option>Compaq</option>
							<option>Apollo</option>
							<option>AstroJet</option>
							<option>Bryce</option>
							<option>Hasler</option>
							<option>Mimaki</option>
							<option>Mutoh</option>
							<option>NeoPost</option>
							<option>Rena</option>
							<option>Roland</option>
							<option>Secap</option>
							<option>Accessories</option>
						</select>
					</div>
				</div>
				<div class="ti_header_nav_block">
					<div id="ti_header_search_mini">
						<form id="nxt-ac-form" onsubmit="return submitSearch5();" action="http://search.tomatoink.com/search" method="get" name="form5">
							<input type="text" name="keywords" autocomplete="off" value="Type ink or printer model" id="search_v5_5" onfocus="if(this.value=='Type ink or printer model')this.value='';" onblur="if(this.value=='')this.value='Type ink or printer model';" onkeypress="return handleEnter5(this,event)">
							<input type="submit" border="0" onclick="submitSearch5();" value="Find Ink" name="imageField">
						</form>
					</div>
				</div>
			</div>
		</div>
		<div class="ti_cms_contain btcf">
			<div class="ti_header_top_block ti_logo_bar">

				<a href="<?php echo $this->getUrl('') ?>"><img src="<?php echo $this->getSkinUrl('images/ti-assets/ti-logo.png') ?>" alt="Save up to 80% on ink cartridges, toner, and printer accessories at TomatoInk!" id="ti_header_logo"/></a>
			</div>
			<div class="ti_header_top_block ti_hide_767 ti_logo_bar">
				<?php if ($this->getIsHomePage()):?>
				<div class="ti_input_bar" id="ti_header_home_email">

					<form action="<?php echo $this->getUrl(''); ?>Mail_Subscribe/" method="get" id="newsletter-validate-detail">
        <input name="email" type="text" id="newsletter" value="<?php echo $this->__('Enter your email address') ?>" onclick="this.value=='<?php echo $this->__('Enter your email address') ?>'?this.value='':''" onblur="this.value==''?this.value='<?php echo $this->__('Enter your email address') ?>':''" class="input-text required-entry validate-email" />
     	<button type="submit" class="button" title="<?php echo $this->__('Subscribe') ?>"><span><span><?php echo $this->__('Sign Up') ?></span></span></button> 


         </form>
				</div>
				<?php else:?>
				<?php $catalogSearchHelper =  $this->helper('catalogsearch'); ?>
					<div class="ti_input_bar" id="ti_header_site_search">
						<form id="search_mini_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
							<input type="text" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" id="search" value="Find your cartridge" onfocus="if (this.value == 'Find your cartridge') {this.value = '';}" onblur="if (this.value == '') {this.value = 'Find your cartridge';}"/>
							<input type="submit" name="Submit" id="search_submit" value="Search" title="<?php echo $this->__('Search') ?>">
							<div id="search_autocomplete" class="search-autocomplete"></div>
	        <script type="text/javascript">
	        //<![CDATA[
	            var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo $this->__('Search entire store here...') ?>');
	            searchForm.initAutocomplete('<?php echo $catalogSearchHelper->getSuggestUrl() ?>', 'search_autocomplete');
	        //]]>
	        </script>
						</form>
					</div>	
					<ul id="ti_header_searchHelp">		
						<li><a rel="nofollow"><span class="ti_small_text lgTxt">Click here for search help</span></a>
							<div class="ti_cms_gradient_block ti_cms_dropContent" id="ti_header_searchHelpDrop">
								<p><span class="ti_small_text">There are a few ways to find your cartridge or printer model:</span></p>
								<ol>
									<li><span class="ti_small_text">Check your old cartridges for a reference number.</span></li>
									<li><span class="ti_small_text">Find your printer model which should appear on the sticker on your printer.</span></li>
									<li><span class="ti_small_text">Refer to your printer manual to identify the cartridge codes.</span></li>
								</ol>
								<p><span class="ti_small_text">You may type either cartridge code or printer model into the search box to search. Please contact us if you have any further questions.</span></p>
							</div>
						</li>
					</ul>
				</div>
				<?php endif?>
		</div>
			<!-- <div class="ti_header_top_block ti_hide_767 ti_logo_bar" id="ti_site_block">
				<div class="ti_input_bar" id="ti_header_site_search">
					<form id="nxt-ac-form" onsubmit="return submitSearch5();" action="http://search.tomatoink.com/search" method="get" name="form5">
						<input type="text" name="keywords" autocomplete="off" value="Type your ink or printer model..." id="search_v5_5" onfocus="if(this.value=='Type your ink or printer model...')this.value='';" onblur="if(this.value=='')this.value='Type your ink or printer model...';" onkeypress="return handleEnter5(this,event)">
						<input type="submit" border="0" onclick="submitSearch5();" value="Search" name="imageField">
					</form>
				</div>
			</div> !-->
		</div>
		<div id="ti_header_nav_main">
			<div class="ti_cms_contain btcf">
				<ul class="ti_menu ti_hide_767">
					<li><a href="<?php echo $this->getUrl('') ?>hp-compatible-toner-cartridge.html"><span>HP</span></a></li>
					<li><a href="<?php echo $this->getUrl('') ?>brother-printer-ink-toner.html"><span>Brother</span></a></li>
					<li><a href="<?php echo $this->getUrl('') ?>epson-cartridges.html"><span>Epson</span></a></li>
					<li><a href="<?php echo $this->getUrl('') ?>canon-printer-ink-cartridges.html"><span>Canon</span></a></li>
					<li><a href="<?php echo $this->getUrl('') ?>lexmark-printer-cartridges.html"><span>Lexmark</span></a></li>
					<li><a href="<?php echo $this->getUrl('') ?>samsung-printer-ink-toner.html"><span>Samsung</span></a></li>
					<li><a href="<?php echo $this->getUrl('') ?>dell-cartridges.html"><span>Dell</span></a></li>
					<li><a href=""><span>More Brands
						<ul class="ti_sub-menu menu_three_col ti_cms_border_block" id="ti_header_brandsMenu">
							<li><a href="<?php echo $this->getUrl('') ?>kodak-printer-ink-toner.html"><span>Kodak</span></a></li>
							<li><a href="<?php echo $this->getUrl('') ?>konica-minolta-printer-ink-toner-cartridges.html"><span>Konica-Minolta</span></a></li>
							<li><a href="<?php echo $this->getUrl('') ?>okidata-printer-ink-toner.html"><span>Okidata</span></a></li>
							<li><a href="<?php echo $this->getUrl('') ?>xerox-printer-ink-toner.html"><span>Xerox</span></a></li>
							<li><a href="<?php echo $this->getUrl('') ?>kyocera-mita-printer-ink-laser-toner.html"><span>Kyocera-Mita</span></a></li>
							<li><a href="<?php echo $this->getUrl('') ?>pitney-bowes-ink-toner-cartridges.html"><span>Pitney Bowes</span></a></li>
							<li><a href="<?php echo $this->getUrl('') ?>sharp-printer-ink-toner.html"><span>Sharp</span></a></li>
							<li><a href="<?php echo $this->getUrl('') ?>ibm-printer-ink-toner.html"><span>IBM</span></a></li>
							<li><a href="<?php echo $this->getUrl('') ?>ricoh-printer-ink-toner.html"><span>Ricoh</span></a></li>
							<li><a href="<?php echo $this->getUrl('') ?>apple-printer-ink-toner.html"><span>Apple</span></a></li>
							<li><a href="<?php echo $this->getUrl('') ?>compaq-printer-ink-toner.html"><span>Compaq</span></a></li>
							<li><a href="<?php echo $this->getUrl('') ?>apollo-printer-ink-toner.html"><span>Apollo</span></a></li>
							<li><a href=""><span>AstroJet</span></a></li>
							<li><a href=""><span>Bryce</span></a></li>
							<li><a href=""><span>Hasler</span></a></li>
							<li><a href=""><span>Mimaki</span></a></li>
							<li><a href=""><span>Mutoh</span></a></li>
							<li><a href=""><span>NeoPost</span></a></li>
							<li><a href=""><span>Rena</span></a></li>
							<li><a href=""><span>Roland</span></a></li>
							<li><a href=""><span>Secap</span></a></li>
						</ul>
					</span></a></li>
					<li><a href="#"><span>Accessories</span></a>
						<ul class="ti_sub-menu menu_two_col ti_cms_border_block" id="ti_header_lastMenu">
							<li><a href="<?php echo $this->getUrl('') ?>usb-printer-cables.html"><span>Cables</span></a></li>
							<li><a href="<?php echo $this->getUrl('') ?>printer-supply.html"><span>Photo Paper</span></a></li>
						</ul>
					</li>
				</ul>
				<p id="ti_secondary_coupon" class="clear"><strong>This month's special offer:</strong> <span id="ti_secondary_coupon_info"></span> <strong class="ti_secondary_coupon_code" id="ti_secondary_coupon_code"></strong>. <span id="ti_secondary_coupon_exp"></span></p>
			</div>
		</div>
	<div id="ti_header_breadcrumbs"></div>

<?php 
$cart = Mage::getModel('checkout/cart')->getQuote();
//$total_num = Mage::getModel('checkout/cart')->getQuote()->getItemsQty();
//$total_num = $cart->getItemsCount();
$total_num = $cart->getItemsQty();
if ($total_num == "") $total_num=0;

$grandtotal = $cart->getSubtotal();
$shopptingcarthtml="";
foreach ($cart->getAllItems() as $item) {
$shopptingcarthtml .= "<div class='one_half'><a href='" . $this->getUrl('') . $item->getProduct()->getUrlKey() . ".html'><img class='block_center' src='" . $this->helper('catalog/image')->init(Mage::getModel('catalog/product')->load($item->getProductId()), 'small_image') . "'></img></a></div><a href='" . $this->getUrl('') . $item->getProduct()->getUrlKey() . ".html'><div class='one_half'><p>" . $item->getProduct()->getName() . "</p></div></a><div class='ti_cms_separator'></div>";
    //$productId = $item->getProduct()->getId();
    //$productqty = $item->getQty();
    //$productPrice = $item->getProduct()->getPrice();

} 
if ($shopptingcarthtml != "") $shopptingcarthtml .= "<p class='text_center'><span class='altTxt'>Total:<span id='ti_cart_miniProductPrice'>$" . round($grandtotal,2) . "</span></span> <span><a class='ti_button' href='" . $this->getUrl('') . "firecheckout/'><strong>Checkout</strong></a></p>";
?>



<!-- Global Variable Section !-->
<script type="text/javascript">
/*****************************************/
/* toplinks: login section/cart section  */
/* Author: Yiyang     Date 4/25/2014     */
/*****************************************/



var ti_global_islogin = "<?php  if ($this->helper('customer')->isLoggedIn()) echo true; else echo false;  ?>";
var ti_global_customerid = "";
if (ti_global_islogin) ti_global_customerid = "<?php if ($this->helper('customer')->isLoggedIn()) echo Mage::getSingleton('customer/session')->getCustomer()->getId(); ?>";
var ti_global_total   = "<?php echo $total_num ?>";
jQuery(document).ready(function() {
//my account signin/signout
if (ti_global_islogin) {jQuery('#ti_header_login').hide();}
else {jQuery('#ti_header_logout').hide();}

//shopping cart count
jQuery('#ti_header_cartcount').html(ti_global_total);

//shopping cart item
var ti_header_shoppingcartblock = document.getElementById('ti_header_cartitems');
ti_header_shoppingcartblock.innerHTML = "<?php echo $shopptingcarthtml; ?>";


});

</script>
	<!--Body content follows here-->