<form action="" method="post" id="form-confirm-ticket" >
    <h2>
        <?php echo $this->__('Please enter email address used to submit ticket in order to proceed to your support request.') ?>
    </h2>
    <div class="fieldset">
        
        <h2 class="legend"><?php echo $this->__('User Verification') ?></h2>
        
        <ul class="form-list">
            <li class="wide">
                <label for="title" class="required"><em>*</em><?php echo $this->__('Email') ?></label>
                <div class="input-box">
                    <input type="text" name="email" title="<?php echo $this->__('Email') ?>" id="title" class="input-text required-entry" />
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link"><a href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Confirm') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-confirm-ticket', true);
//]]>
</script>
