<meta name="viewport" content="width=device-width">
	
	<!--Fonts for all pages
	<link href='//fonts.googleapis.com/css?family=Oleo+Script' rel='stylesheet' type='text/css'>
	<link href='//fonts.googleapis.com/css?family=Raleway:400,700,300&subset=all' rel='stylesheet' type='text/css'>-->
	<!--end fonts-->
	
	<!--[if gte IE 9]>
  		<style type="text/css">
    		.gradient, .ti_cms_gradient_block {
       		filter: none;
   			 }
  		</style>
	<![endif]-->
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.contentcarousel.header.js') ?>"></script>
	<?php $current_url = $this->getUrl(''); ?>
	<script type="text/javascript">
		var homepage = "<?php if ($this->getIsHomePage()) echo 'true'; else echo 'false'?>";
		var ti_skin_url = "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>";
		var ti_global_url = "<?php echo $current_url;?>";
		if (ti_global_url.match(/index.php/)) ti_global_url = ti_global_url.match(/.*(?=index.php\/)/);

	</script>
    <div id="ti_top_link"></div>

	<div id="ti_header_row">
		<?php 
		
		$getCouponModel = Mage::getResourceModel('compandsave_variable/coupon_collection')
				->addFieldToFilter('entity_type_id','Coupon')
				->addFieldToFilter('status','1')
				->addFieldToFilter('visibility','1')
				->getFirstItem()
				->load();
				
		?>
		<div class="ti_cms_contain ti_hide_767" id="ti_main_coupon">
			
			<p id="ti_header_coupon_desc">
				<span id="ti_header_coupon_info"><?php echo $getCouponModel['description'];?></span><br>
				<span id="ti_header_coupon_code"><?php echo $getCouponModel['value']; ?></span><br>
				<span id="ti_header_coupon_exp" class="ti_small_text"><?php echo $getCouponModel['expiry_date']; ?></span>
			</p>
			<p id="ti_header_click_coupon"><span>Fresh Deals</span><br>Get this month's coupon.</p>
			<div id="ti_main_coupon_arrow"></div>
		</div>
		<div id="ti_header_quick_links" class="btcf">
			<div class="ti_cms_contain">
				<div class="ti_header_top_block ti_hide_767">
					<p><a href="<?php echo $current_url;?>shipping-policy"><strong>Free shipping on orders of $50 or more!</strong> Reg: $3.99</a></p>
				</div>
				<div class="ti_header_top_block ti_hide_767">
					
						<?php echo $this->getChildHtml('topLinks') ?>
					
				</div>
				<div class="ti_header_nav_block clear">
					<div id="ti_header_nav_mini">
						<select id="ti_header_mininav">
							<option selected="selected" disabled="disabled">Shop by...</option>
							<option value="hp-compatible-toner-cartridge.html">HP</option>
							<option value="brother-printer-ink-toner.html">Brother</option>
							<option value="epson-cartridges.html">Epson</option>
							<option value="canon-printer-ink-cartridges.html">Canon</option>
							<option value="lexmark-printer-cartridges.html">Lexmark</option>
							<option value="samsung-printer-ink-toner.html">Samsung</option>
							<option value="dell-cartridges.html">Dell</option>
							<option value="kodak-printer-ink-toner.html">Kodak</option>
							<option value="konica-minolta-printer-ink-toner-cartridges.html">Konica-Minolta</option>
							<option value="okidata-printer-ink-toner.html">Okidata</option>
							<option value="xerox-printer-ink-toner.html">Xerox</option>
							<option value="kyocera-mita-printer-ink-laser-toner.html">Kyocera-Mita</option>
							<option value="pitney-bowes-ink-toner-cartridges.html">Pitney Bowes</option>
							<option value="sharp-printer-ink-toner.html">Sharp</option>
							<option value="ibm-printer-ink-toner.html">IBM</option>
							<option value="ricoh-printer-ink-toner.html">Ricoh</option>
							<option value="apple-printer-ink-toner.html">Apple</option>
							<option value="compaq-printer-ink-toner.html">Compaq</option>
							<option value="apollo-printer-ink-toner.html">Apollo</option>
							<option>AstroJet</option>
							<option>Bryce</option>
							<option>Hasler</option>
							<option>Mimaki</option>
							<option>Mutoh</option>
							<option>NeoPost</option>
							<option>Rena</option>
							<option>Roland</option>
							<option>Secap</option>
							<option>Accessories</option>
						</select>
						<script type="text/javascript">
							jQuery("#ti_header_mininav").change(function() {

        						var dataString = jQuery(this).val();
								window.location.href = ti_global_url + dataString;

        

        					});
						</script>
					</div>
				</div>
				<div class="ti_header_nav_block">
					<div id="ti_header_search_mini">
						<!-- <form id="nxt-ac-form" onsubmit="return submitSearch5();" action="http://search.tomatoink.com/search" method="get" name="form5">
							<input type="text" name="keywords" autocomplete="off" value="Type ink or printer model" id="search_v5_5" onfocus="if(this.value=='Type ink or printer model')this.value='';" onblur="if(this.value=='')this.value='Type ink or printer model';" onkeypress="return handleEnter5(this,event)">
							<input type="submit" border="0" onclick="submitSearch5();" value="Find Ink" name="imageField">
						</form> !-->
						<?php $catalogSearchHelper =  $this->helper('catalogsearch'); ?>
						<form id="search_mini_form2" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
							<input type="text" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" id="search2" placeholder="Ink or printer model" />
							<input type="submit" name="Submit" id="search_submit2" value="Search" title="<?php echo $this->__('Search') ?>" />
							</form>
	        <script type="text/javascript">
	        //<![CDATA[
	            //var searchForm = new Varien.searchForm('search_mini_form2', 'search2', '<?php echo $this->__('Type ink or printer model') ?>');
	            //searchForm.initAutocomplete('<?php echo $catalogSearchHelper->getSuggestUrl() ?>', 'search_autocomplete');
	        //]]>
	        </script>
						



					</div>
				</div>
			</div>
		</div>
		<div class="ti_cms_contain text_center btcf">
			<div class="ti_header_top_block ti_logo_bar">

				<a href="<?php echo $current_url ?>" class="ti_header_logo_border"><img src="<?php echo $this->getSkinUrl('images/ti-assets/ti-logo.png') ?>" alt="Save up to 80% on ink cartridges, toner, and printer accessories at TomatoInk!" id="ti_header_logo"/></a>
			</div>
			<div class="ti_header_top_block ti_hide_767 ti_logo_bar">
				<?php //if ($this->getIsHomePage()):?>
				<!--<div class="ti_input_bar" id="ti_header_home_email">

					<form action="<?php //echo $current_url; ?>Mail_Subscribe/" method="get" id="newsletter-validate-detail">
        <input name="email" type="email" id="newsletter" placeholder="<?php //echo $this->__('Enter your email address') ?>" class="input-text required-entry validate-email" />
     	<button type="submit" class="button" title="<?php //echo $this->__('Subscribe') ?>"><?php //echo $this->__('Sign Up') ?></button> 


         </form>
				</div>!-->
				<?php //else:?>
				<?php $catalogSearchHelper =  $this->helper('catalogsearch'); ?>
					<div class="ti_input_bar" id="ti_header_site_search">
						<form id="search_mini_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
							<input type="search" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" id="search" placeholder="Type your printer or ink model..." />
							<input type="submit" name="Submit" id="search_submit" value="Search" title="<?php echo $this->__('Search') ?>">
							<div id="search_autocomplete" class="search-autocomplete"></div>
	        <script type="text/javascript">
	        //<![CDATA[
	            var searchForm = new Varien.searchForm('search_mini_form', 'search', '');
	            // echo $this->__('Type ink or printer model') 
	            searchForm.initAutocomplete('<?php echo $catalogSearchHelper->getSuggestUrl() ?>', 'search_autocomplete');
	        //]]>
	        </script>
						</form>
					</div>	
					<!--<ul id="ti_header_searchHelp">		
						<li><a rel="nofollow"><span class="ti_small_text lgTxt">Click here for search help</span></a>
							<div class="ti_cms_gradient_block ti_cms_dropContent" id="ti_header_searchHelpDrop">
								<p><span class="ti_small_text">There are a few ways to find your cartridge or printer model:</span></p>
								<ul class="ti_bullet">
									<li><span class="ti_small_text">Check your old cartridges for a reference number.</span></li>
									<li><span class="ti_small_text">Find your printer model which should appear on the sticker on your printer.</span></li>
									<li><span class="ti_small_text">Refer to your printer manual to identify the cartridge codes.</span></li>
								</ul>
								<p><span class="ti_small_text">You may type either cartridge code or printer model into the search box to search. Please contact us if you have any further questions.</span></p>
							</div>
						</li>
					</ul>-->
				</div>
				<?php //endif?>
		</div>
			<!-- <div class="ti_header_top_block ti_hide_767 ti_logo_bar" id="ti_site_block">
				<div class="ti_input_bar" id="ti_header_site_search">
					<form id="nxt-ac-form" onsubmit="return submitSearch5();" action="http://search.tomatoink.com/search" method="get" name="form5">
						<input type="text" name="keywords" autocomplete="off" value="Type your ink or printer model..." id="search_v5_5" onfocus="if(this.value=='Type your ink or printer model...')this.value='';" onblur="if(this.value=='')this.value='Type your ink or printer model...';" onkeypress="return handleEnter5(this,event)">
						<input type="submit" border="0" onclick="submitSearch5();" value="Search" name="imageField">
					</form>
				</div>
			</div> !-->
		</div>
		<div id="ti_header_nav_main">
			<div class="ti_cms_contain btcf">
				<ul class="ti_menu ti_hide_767">
					<li><a href="<?php echo $current_url ?>hp-compatible-toner-cartridge.html"><span>HP</span></a></li>
					<li><a href="<?php echo $current_url ?>brother-printer-ink-toner.html"><span>Brother</span></a></li>
					<li><a href="<?php echo $current_url ?>epson-cartridges.html"><span>Epson</span></a></li>
					<li><a href="<?php echo $current_url ?>canon-printer-ink-cartridges.html"><span>Canon</span></a></li>
					<li><a href="<?php echo $current_url ?>lexmark-printer-cartridges.html"><span>Lexmark</span></a></li>
					<li><a href="<?php echo $current_url ?>samsung-printer-ink-toner.html"><span>Samsung</span></a></li>
					<li><a href="<?php echo $current_url ?>dell-cartridges.html"><span>Dell</span></a></li>
					<li><a href="" aria-haspopup="true"><span>More Brands
						<ul class="ti_sub-menu menu_three_col ti_cms_border_block" id="ti_header_brandsMenu">
							<li><a href="<?php echo $current_url ?>kodak-printer-ink-toner.html"><span>Kodak</span></a></li>
							<li><a href="<?php echo $current_url ?>konica-minolta-printer-ink-toner-cartridges.html"><span>Konica-Minolta</span></a></li>
							<li><a href="<?php echo $current_url ?>okidata-printer-ink-toner.html"><span>Okidata</span></a></li>
							<li><a href="<?php echo $current_url ?>xerox-printer-ink-toner.html"><span>Xerox</span></a></li>
							<li><a href="<?php echo $current_url ?>kyocera-mita-printer-ink-laser-toner.html"><span>Kyocera-Mita</span></a></li>
							<li><a href="<?php echo $current_url ?>pitney-bowes-ink-toner-cartridges.html"><span>Pitney Bowes</span></a></li>
							<li><a href="<?php echo $current_url ?>sharp-printer-ink-toner.html"><span>Sharp</span></a></li>
							<li><a href="<?php echo $current_url ?>ibm-printer-ink-toner.html"><span>IBM</span></a></li>
							<li><a href="<?php echo $current_url ?>ricoh-printer-ink-toner.html"><span>Ricoh</span></a></li>
							<li><a href="<?php echo $current_url ?>apple-printer-ink-toner.html"><span>Apple</span></a></li>
							<li><a href="<?php echo $current_url ?>compaq-printer-ink-toner.html"><span>Compaq</span></a></li>
							<li><a href="<?php echo $current_url ?>apollo-printer-ink-toner.html"><span>Apollo</span></a></li>
							<li><a href="<?php echo $current_url ?>other-brands-printer-ink-toner-cartridges/astrojet-series-ink-and-toner-cartridges.html"><span>AstroJet</span></a></li>
							<li><a href="<?php echo $current_url ?>other-brands-printer-ink-toner-cartridges/bryce-series-ink-and-toner-cartridges.html"><span>Bryce</span></a></li>
							<li><a href="<?php echo $current_url ?>other-brands-printer-ink-toner-cartridges/hasler-series-ink-and-toner-cartridges.html"><span>Hasler</span></a></li>
							<li><a href="<?php echo $current_url ?>other-brands-printer-ink-toner-cartridges/mimaki-series-ink-and-toner-cartridges.html"><span>Mimaki</span></a></li>
							<li><a href="<?php echo $current_url ?>other-brands-printer-ink-toner-cartridges/mutoh-series-ink-and-toner-cartridges.html"><span>Mutoh</span></a></li>
							<li><a href="<?php echo $current_url ?>other-brands-printer-ink-toner-cartridges/neopost-series-ink-and-toner-cartridges.html"><span>NeoPost</span></a></li>
							<li><a href="<?php echo $current_url ?>other-brands-printer-ink-toner-cartridges/rena-series-ink-and-toner-cartridges.html"><span>Rena</span></a></li>
							<li><a href="<?php echo $current_url ?>other-brands-printer-ink-toner-cartridges/roland-series-ink-and-toner-cartridges.html"><span>Roland</span></a></li>
							<li><a href="<?php echo $current_url ?>other-brands-printer-ink-toner-cartridges/secap-series-ink-and-toner-cartridges.html"><span>Secap</span></a></li>
						</ul>
					</span></a></li>
					<li><a href="#" aria-haspopup="true"><span>Accessories</span></a>
						<ul class="ti_sub-menu menu_one_col ti_cms_border_block" id="ti_header_lastMenu">
							<li><a href="<?php echo $current_url ?>usb-printer-cables.html"><span>Cables</span></a></li>
							<li><a href="<?php echo $current_url ?>printer-supply.html"><span>Photo Paper</span></a></li>
						</ul>
					</li>
				</ul>
				<!--<p id="ti_secondary_coupon" class="clear"><strong>This month's special offer:</strong> <span id="ti_secondary_coupon_info"></span> <strong class="ti_secondary_coupon_code" id="ti_secondary_coupon_code"></strong>. <span id="ti_secondary_coupon_exp"></span></p>-->
			</div>
		</div>
	<div class="ti_cms_contain btcf">
		<div id="ti_header_breadcrumbs"></div>
		<?php if ($this->getIsHomePage()):?>
			<style type="text/css"> #ti_header_breadcrumbs {display:none;} </style>
		<?php endif; ?>
	</div>



