<?php
if (!Mage::getStoreConfig('knowledgebase/general/product')) {
    return;
}
$collection = $this->getCollection();
if (count($collection)) :?>
    <div class="knowledgebase-block block-related-articles">
        <h2><?php echo $this->__('Related Article') ?></h2>
        <ol>
        <?php foreach ($collection as $_faq) :?>
            <li class="item">
                <a href="<?php echo $this->getUrl(
                    'knowledgebase/index/view', array('faq' => $_faq->getIdentifier()))
                ?>"><?php echo $_faq->getTitle() ?></a>&nbsp;
            </li>
        <?php endforeach; ?>
        </ol>
    </div>
<?php endif; ?>