<?php echo $this->getChildHtml('items_before'); ?>

<?php
    echo $this->getMessagesBlock()->getGroupedHtml();
    $this->getMessagesBlock()->getMessageCollection()->clear();
?>

<div id="checkout-review-table-wrapper">
    <table class="data-table" id="checkout-review-table">
        <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
        <col class="ti_table_checkout_productName" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
        <col width="1" />
        <col width="1" />
        <?php endif; ?>
        <thead>
            <tr class="ti_cart_total">
                <th class="ti_table_checkout_productName" rowspan="<?php echo $rowspan ?>"><span><?php echo $this->__('Item') ?></span></th>
                <th class="ti_table_checkout_productPrice" colspan="<?php echo $colspan ?>" class="a-center"><span><?php echo $this->__('Price') ?></span></th>
                <th class="ti_table_checkout_productQTY" rowspan="<?php echo $rowspan ?>" class="a-center"><span><?php echo $this->__('Qty') ?></span></th>
                <th class="ti_table_checkout_productSubtotal" colspan="<?php echo $colspan ?>" class="a-right"><span><?php echo $this->__('Subtotal') ?></span></th>
            </tr>
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <tr>
                    <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                </tr>
            <?php endif; ?>
        </thead>
        <?php echo $this->getChildHtml('totals'); ?>
        <tbody>
        <?php foreach($this->getItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item)?>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
<?php echo $this->getChildHtml('items_after'); ?>
<script type="text/javascript">
//<![CDATA[
    decorateTable('checkout-review-table');
    truncateOptions();
//]]>
</script>
