<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/articles/ti-article.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/articles/become_reseller/ti-become_reseller.css" type="text/css" />

<?php 

require(Mage::getBaseDir().DS.'yy'.DS.'recaptchalib.php');

$message = '';
 if (isset($_POST['CustomerEmail'])) {
    	  $privatekey = "6LciLvwSAAAAALA7fGlCyeRb4Qp8S68dw3uW5Ei4";
  $resp = recaptcha_check_answer ($privatekey,
                                $_SERVER["REMOTE_ADDR"],
                                $_POST["recaptcha_challenge_field"],
                                $_POST["recaptcha_response_field"]);

  if (!$resp->is_valid) {
    // What happens when the CAPTCHA was entered incorrectly
    $secure_message = "Sorry, Security Code is wrong";
  } else {
    $secure_message = "Thanks for contacting us, we will reply you soon";
    //send email
    $name = $_POST["CustomerName"];
    $company = $_POST["CompanyName"];
    $email = $_POST["CustomerEmail"];
    $phone = $_POST["CompanyPhone"];
    $address = $_POST["CompanyAddress"];
    $howfindus = $_POST["HowFindUs"];
    $message = $_POST["CustomerComments"];


$to      = 'yiyangh@compandsave.com';
$subject = 'become reseller email';
$message = "Name: " . $name . "\nCompany: " . $company . "\nEmail: " . $email . "\nPhone: " . $phone . "\nAddress: " . $address . "\nHow Do you find us: " . $howfindus . "\nMessage: " . $message; 
$headers = 'From: bestreseller@compandsave.com' . "\r\n" . 'X-Mailer: PHP/' . phpversion();

mail($to, $subject, $message, $headers);
  }

    }

?>


<div class="ti-cms-articleContent_area">
	<h1 class="dgTxt">Reseller and Volume Purchase</h1>
	<div class="two_third">
	<p>Since most of our products are purchased directly from the factory in large quantities, we can offer very competitive wholesale pricing for resellers or large volume buyers.</p>
	<p>If you are interested in setting up a wholesale account with us, please call <strong class="lgTxt">1.877.777.0127 Ext. 115</strong> for details.</p>
	<div class="ti_cms_separator">&nbsp;</div>
	<h2 class="altTxt">Need a Quote?</h2>
	<form action="" method="post" name="YourForm" id="reseller_form">
	<p>Please fill in the Wholesale Pricing Request form below. We will do our best to reply to you within 1-2 business days.</p>
	<?php if (isset($secure_message)) echo $secure_message . "<br>"; ?>
	<?php if ($secure_message != "Thanks for contacting us! We will be in touch with you soon!"): ?>
	<div id="warning_message" class='validation-advice'></div>
	<div class="ti-required-entry one">
		<label class="ti_cms_labelHide"> <input id="CustomerName" class="textArea ti-cms-inputFull" onfocus="if(this.value=='Contact Person')this.value='';" onblur="if(this.value=='')this.value='Contact Person';" type="text" name="CustomerName" value="Contact Person" /> <span>Contact Person:</span> </label>
	</div>
	<div class="ti-required-entry one">
		<label class="ti_cms_labelHide"> <input id="CompanyName" class="textArea ti-cms-inputFull" onfocus="if(this.value=='Company Name')this.value='';" onblur="if(this.value=='')this.value='Company Name';" type="text" name="CompanyName" value="Company Name" /> <span>Company Name:</span> </label>
	</div>
	<div class="ti-required-entry one">
		<label class="ti_cms_labelHide"> <input id="CustomerEmail" class="textArea ti-cms-inputFull" onfocus="if(this.value=='Email Address')this.value='';" onblur="if(this.value=='')this.value='Email Address';" type="text" name="CustomerEmail" value="Email Address" /> <span>Email Address:</span> </label>
	</div>
	<div class="one">
		<label class="ti_cms_labelHide"> <input id="CompanyPhone" class="textArea ti-cms-inputFull" onfocus="if(this.value=='Phone Number')this.value='';" onblur="if(this.value=='')this.value='Phone Number';" type="text" name="CompanyPhone" value="Phone Number" /> <span>Phone:</span> </label>
	</div>
	<div class="one">
		<label class="ti_cms_labelHide"> <input id="CompanyAddress" class="textArea ti-cms-inputFull" onfocus="if(this.value=='Address')this.value='';" onblur="if(this.value=='')this.value='Address';" type="text" name="CompanyAddress" value="Address" /> <span>Address:</span> </label>
	</div>
	<div class="one">
		<label><span>How did you find us?</span></label>
		<div class="ti_select_barContainer">
			<select id="HowFindUs" class="selectBox" name="HowFindUs"> 
				<option value="Not Specify">Please select...</option> 
				<option value="Google">Google</option> 
				<option value="Yahoo!">Yahoo!</option> 
				<option value="MSN">MSN</option> 
				<option value="Facebook">Facebook</option> 
				<option value="Twitter">Twitter</option> 
				<option value="Referral">Referred by friends</option> <option value="Others">Others</option> 
			</select>
		</div>
	</div>
	<div class="one">
		<label><span>Include a message:</span> <textarea id="CustomerComments" class="ti-cms-inputFull" name="CustomerComments" rows="8"></textarea> </label>
	</div>
	<div class="one ti_cms_gradient_block btcf">
	<p><strong><span class="altTxt">*</span> Please enter the security code shown below</strong>, which helps us ensure this entry is being submitted by a human and not an automated computer script.</p>

	 <script type="text/javascript">
	 var RecaptchaOptions = {
	    theme : 'clean'
	 };
	 </script>

	 
	<?php 
	 $publickey = "6LciLvwSAAAAABBaalYw1CH0aKwFgeyWH2xLHjhE"; // you got this from the signup page
	 echo recaptcha_get_html($publickey);

	?>
	</div>
	<!--<script type="text/javascript">var RecaptchaOptions = {   theme : 'white',   tabindex : 0};</script>
				<script type="text/javascript" src="https://www.google.com/recaptcha/api/challenge?k=6LdSHNUSAAAAAOigr5tNXPKON3RvL5JaAmKCAIX-"></script>
				<noscript>
					<iframe src="https://www.google.com/recaptcha/api/noscript?k=6LdSHNUSAAAAAOigr5tNXPKON3RvL5JaAmKCAIX-" frameborder="1"></iframe><br>
					<textarea name="recaptcha_challenge_field" rows="3"cols="40"></textarea>
					<input type="hidden" name="recaptcha_response_field"value="manual_challenge">
				</noscript>	<!-- Create the recaptcha element !--> <input id="ti_br_btnSendMsg" class="ti-cms-floatRight" type="button" name="Send" value="Send Message" /></form></div>
	<!-- left column OVER -->
		
	<?php else: ?>
		<h1>Thanks</h1>
		<?php endif; ?>
	<div class="one_third">
		<div class="ti_block_inner ti_cms_gradient_block">
			<p>The following link brings you to our current wholesale packs:</p>
			<p><a class="lgTxt" href="http://www.tomatoink.com/Wholesale_Ink_Cartridges_and_Toner_Cartridges_Pack_s/40.htm">Wholesale Packs</a></p>
			<p>If you would like any further information, please contact us through phone <strong class="lgTxt">1.877.777.0127 Ext. 115</strong>, or drop us a line using the form on this page.</p>
		</div>
	</div>
</div>




<script type='text/javascript'>
jQuery('#ti_br_btnSendMsg').click(function() {

	if (jQuery("#CustomerName").val() == 'Contact Person') {
		jQuery("#warning_message").html("Customer Name is empty");
	}
	else if (jQuery("#CompanyName").val() == 'Company Name') {
		jQuery("#warning_message").html("Company Name is empty");
	}
	else if (jQuery("#CustomerEmail").val() == 'Email Address') {
		jQuery("#warning_message").html("Email address is empty");
	}
	else if (!validateEmail(jQuery("#CustomerEmail").val())) {
		jQuery("#warning_message").html("Email address is invalide");
	}

	else {
		//submit form
		jQuery("#reseller_form").submit();
	}
        
});



</script>
