<form action="<?php echo $this->getAction() ?>" method="post" id="form-ticket" enctype="multipart/form-data">
    <div class="fieldset block ti_cms_gradient_block one btcf">

        <h2 class="legend"><?php echo $this->__('Add New Ticket') ?></h2>

        <ul class="form-list">
            <?php if(!Mage::getSingleton('customer/session')->isLoggedIn()) :?>

            <li class="fields one_half">
                <div class="field">
                    <label for="title" class="required ti_cms_labelHide"><span><?php echo $this->__('Title') ?></span></label>
                    <div class="input-box ti-required-entry">
                        <input type="text" name="title" title="<?php echo $this->__('Title') ?>" id="title" class="input-text required-entry" placeholder="Name this RMA" />
                    </div>
                </div>

                <div class="field one_half">
                    <label for="email" class="required ti_cms_labelHide"><span><?php echo Mage::helper('contacts')->__('Email') ?></span></label>
                    <div class="input-box ti-required-entry">
                        <input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="email" placeholder="Email" />
                    </div>
                </div>
            </li>
            <?php else :?>
            <li class="wide one">
                <label for="title" class="required ti_cms_labelHide"><span><?php echo $this->__('Title') ?></span></label>
                <div class="input-box ti-required-entry">
                    <input type="text" name="title" title="<?php echo $this->__('Title') ?>" id="title" class="input-text required-entry" placeholder="Name this RMA" />
                </div>
            </li>
            <?php endif; ?>

            <li class="fields one">
                <div class="field one_half">
                    <label for="department" class="required"><span><?php echo $this->__('Department') ?></span></label>
                    <div class="input-box ti-required-entry btcf">
                        <div class="ti_select_barContainer btcf">
                            <?php echo $this->getDepartmentHtmlSelect() ?>
                        </div>
                    </div>
                </div>
                <?php if(Mage::getStoreConfig("helpmate/ticketForm/usePriorityOnFrontend")) :?>
                <div class="field one_half">
                    <label for="priority" class="required"><span><?php echo $this->__('Priority') ?></span></label>
                    <div class="input-box ti-required-entry btcf">
                        <div class="ti_select_barContainer btcf">
                            <?php echo $this->getPriorityHtmlSelect() ?>
                        </div>
                    </div>
                </div>
                <?php endif;?>
            </li>

            <li class="wide one">
                
                <div class="input-box one">
                    <label class="required ti-required-entry" for="text"><span><?php echo $this->__('Message') ?></span></label>
                    <textarea id="text" class="input-text required-entry one" title="<?php echo $this->__('Message') ?>" name="text" cols="5" rows="10" placeholder="Please type your message"></textarea>
                </div>
            </li>
            
            <?php echo $this->getChildHtml('form.additional.info'); ?>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p><button type="submit" title="<?php echo $this->__('Save Ticket') ?>" class="button"><span><span><?php echo $this->__('Save Ticket') ?></span></span></button>
        <span class="back-link"><a href="<?php echo $this->getBackUrl() ?>" class="ti_button"><?php echo $this->__('Back') ?></a></span></p>
        
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-ticket', true);
//]]>
</script>
