<?php if ($this->isPossibleFireCheckout()):?>
    <button type="button" title="<?php echo $this->__('Checkout Now') ?>" class="button btn-proceed-checkout one_third btn-checkout checkout-types<?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?> onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';"><span class="icon-lock"><?php echo $this->__('Checkout Now') ?></span></button>
<?php endif?>
